

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST"},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.weights_1_U"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bias_1_U"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.weights_U"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bias_U"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.weights_2_U"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bias_2_U"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.linear_64_1_float_float_weights_1_U"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.in_buf_U"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.l1_U"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.l2_U"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.l3_U"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_task_detection_accel_Pipeline_VITIS_LOOP_29_1_fu_177"},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_task_detection_accel_Pipeline_VITIS_LOOP_29_1_fu_177.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_task_detection_accel_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_23_2_fu_185"},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_task_detection_accel_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_23_2_fu_185.mul_9ns_9ns_16_1_1_U4"},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_task_detection_accel_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_23_2_fu_185.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_task_detection_accel_Pipeline_VITIS_LOOP_32_3_VITIS_LOOP_38_4_fu_193"},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_task_detection_accel_Pipeline_VITIS_LOOP_32_3_VITIS_LOOP_38_4_fu_193.fadd_32ns_32ns_32_1_full_dsp_1_U8"},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_task_detection_accel_Pipeline_VITIS_LOOP_32_3_VITIS_LOOP_38_4_fu_193.mul_9ns_9ns_16_1_1_U10"},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_task_detection_accel_Pipeline_VITIS_LOOP_32_3_VITIS_LOOP_38_4_fu_193.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "21", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_task_detection_accel_Pipeline_VITIS_LOOP_64_1_VITIS_LOOP_68_2_fu_203"},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_task_detection_accel_Pipeline_VITIS_LOOP_64_1_VITIS_LOOP_68_2_fu_203.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "23", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_task_detection_accel_Pipeline_VITIS_LOOP_77_3_VITIS_LOOP_83_4_fu_211"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_task_detection_accel_Pipeline_VITIS_LOOP_77_3_VITIS_LOOP_83_4_fu_211.fadd_32ns_32ns_32_1_full_dsp_1_U18"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_task_detection_accel_Pipeline_VITIS_LOOP_77_3_VITIS_LOOP_83_4_fu_211.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "26", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_task_detection_accel_Pipeline_VITIS_LOOP_109_1_VITIS_LOOP_113_2_fu_221"},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_task_detection_accel_Pipeline_VITIS_LOOP_109_1_VITIS_LOOP_113_2_fu_221.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "28", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_task_detection_accel_Pipeline_VITIS_LOOP_122_3_VITIS_LOOP_128_4_fu_229"},
	{"ID" : "29", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_task_detection_accel_Pipeline_VITIS_LOOP_122_3_VITIS_LOOP_128_4_fu_229.fadd_32ns_32ns_32_1_full_dsp_1_U26"},
	{"ID" : "30", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_task_detection_accel_Pipeline_VITIS_LOOP_122_3_VITIS_LOOP_128_4_fu_229.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "31", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_task_detection_accel_Pipeline_VITIS_LOOP_156_1_fu_239"},
	{"ID" : "32", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_task_detection_accel_Pipeline_VITIS_LOOP_156_1_fu_239.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "33", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_task_detection_accel_Pipeline_VITIS_LOOP_166_2_fu_245"},
	{"ID" : "34", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_task_detection_accel_Pipeline_VITIS_LOOP_166_2_fu_245.fadd_32ns_32ns_32_2_full_dsp_1_U33"},
	{"ID" : "35", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_task_detection_accel_Pipeline_VITIS_LOOP_166_2_fu_245.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "36", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U"},
	{"ID" : "37", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_r_s_axi_U"},
	{"ID" : "38", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem0_m_axi_U"},
	{"ID" : "39", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem1_m_axi_U"},
	{"ID" : "40", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fmul_32ns_32ns_32_3_max_dsp_1_U39"}]}
set DependenceCheckSize 0
