# Inferred from syn.compile.pipeline_loops=64
set_directive_pipeline yolo_npu_v2_core/VITIS_LOOP_123_17
# Inferred from performance & pipeline pragmas/directives
set_directive_loop_flatten yolo_npu_v2_core/VITIS_LOOP_45_4
set_directive_loop_flatten yolo_npu_v2_core/VITIS_LOOP_43_3
set_directive_loop_flatten yolo_npu_v2_core/VITIS_LOOP_67_7
set_directive_loop_flatten yolo_npu_v2_core/VITIS_LOOP_65_6
set_directive_loop_flatten yolo_npu_v2_core/VITIS_LOOP_94_13
set_directive_loop_flatten yolo_npu_v2_core/VITIS_LOOP_93_12
set_directive_loop_flatten yolo_npu_v2_core/VITIS_LOOP_92_11
set_directive_loop_flatten yolo_npu_v2_core/VITIS_LOOP_125_18
set_directive_loop_flatten yolo_npu_v2_core/VITIS_LOOP_195_25
set_directive_loop_flatten yolo_npu_v2_core/VITIS_LOOP_193_24
