[hls]
relative_roots=/home/dlohchab/projects/Verilog/DVCON/task_detection_tpu/yolo_npu
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=yolo_npu_v2_core/VITIS_LOOP_116_16 
# Inferred from performance & pipeline pragmas/directives
syn.directive.loop_flatten=yolo_npu_v2_core/VITIS_LOOP_38_3  
syn.directive.loop_flatten=yolo_npu_v2_core/VITIS_LOOP_36_2  
syn.directive.loop_flatten=yolo_npu_v2_core/VITIS_LOOP_60_6  
syn.directive.loop_flatten=yolo_npu_v2_core/VITIS_LOOP_58_5  
syn.directive.loop_flatten=yolo_npu_v2_core/VITIS_LOOP_87_12  
syn.directive.loop_flatten=yolo_npu_v2_core/VITIS_LOOP_86_11  
syn.directive.loop_flatten=yolo_npu_v2_core/VITIS_LOOP_85_10  
syn.directive.loop_flatten=yolo_npu_v2_core/VITIS_LOOP_118_17  
syn.directive.loop_flatten=yolo_npu_v2_core/VITIS_LOOP_178_24  
syn.directive.loop_flatten=yolo_npu_v2_core/VITIS_LOOP_176_23  


