# Inferred from syn.compile.pipeline_loops=64
set_directive_pipeline yolo_npu_v2_core/VITIS_LOOP_116_16
# Inferred from performance & pipeline pragmas/directives
set_directive_loop_flatten yolo_npu_v2_core/VITIS_LOOP_38_3
set_directive_loop_flatten yolo_npu_v2_core/VITIS_LOOP_36_2
set_directive_loop_flatten yolo_npu_v2_core/VITIS_LOOP_60_6
set_directive_loop_flatten yolo_npu_v2_core/VITIS_LOOP_58_5
set_directive_loop_flatten yolo_npu_v2_core/VITIS_LOOP_87_12
set_directive_loop_flatten yolo_npu_v2_core/VITIS_LOOP_86_11
set_directive_loop_flatten yolo_npu_v2_core/VITIS_LOOP_85_10
set_directive_loop_flatten yolo_npu_v2_core/VITIS_LOOP_118_17
set_directive_loop_flatten yolo_npu_v2_core/VITIS_LOOP_178_24
set_directive_loop_flatten yolo_npu_v2_core/VITIS_LOOP_176_23
