[hls]
relative_roots=/home/dlohchab/projects/Verilog/DVCON/task_detection_tpu/yolo_npu
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=yolo_npu_v2_core/VITIS_LOOP_123_17 
# Inferred from performance & pipeline pragmas/directives
syn.directive.loop_flatten=yolo_npu_v2_core/VITIS_LOOP_45_4  
syn.directive.loop_flatten=yolo_npu_v2_core/VITIS_LOOP_43_3  
syn.directive.loop_flatten=yolo_npu_v2_core/VITIS_LOOP_67_7  
syn.directive.loop_flatten=yolo_npu_v2_core/VITIS_LOOP_65_6  
syn.directive.loop_flatten=yolo_npu_v2_core/VITIS_LOOP_94_13  
syn.directive.loop_flatten=yolo_npu_v2_core/VITIS_LOOP_93_12  
syn.directive.loop_flatten=yolo_npu_v2_core/VITIS_LOOP_92_11  
syn.directive.loop_flatten=yolo_npu_v2_core/VITIS_LOOP_125_18  
syn.directive.loop_flatten=yolo_npu_v2_core/VITIS_LOOP_195_25  
syn.directive.loop_flatten=yolo_npu_v2_core/VITIS_LOOP_193_24  


