// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module yolo_npu_v2_core_yolo_npu_v2_core_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_38_3_VITIS_LOOP_40_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_0_AWVALID,
        m_axi_gmem_0_AWREADY,
        m_axi_gmem_0_AWADDR,
        m_axi_gmem_0_AWID,
        m_axi_gmem_0_AWLEN,
        m_axi_gmem_0_AWSIZE,
        m_axi_gmem_0_AWBURST,
        m_axi_gmem_0_AWLOCK,
        m_axi_gmem_0_AWCACHE,
        m_axi_gmem_0_AWPROT,
        m_axi_gmem_0_AWQOS,
        m_axi_gmem_0_AWREGION,
        m_axi_gmem_0_AWUSER,
        m_axi_gmem_0_WVALID,
        m_axi_gmem_0_WREADY,
        m_axi_gmem_0_WDATA,
        m_axi_gmem_0_WSTRB,
        m_axi_gmem_0_WLAST,
        m_axi_gmem_0_WID,
        m_axi_gmem_0_WUSER,
        m_axi_gmem_0_ARVALID,
        m_axi_gmem_0_ARREADY,
        m_axi_gmem_0_ARADDR,
        m_axi_gmem_0_ARID,
        m_axi_gmem_0_ARLEN,
        m_axi_gmem_0_ARSIZE,
        m_axi_gmem_0_ARBURST,
        m_axi_gmem_0_ARLOCK,
        m_axi_gmem_0_ARCACHE,
        m_axi_gmem_0_ARPROT,
        m_axi_gmem_0_ARQOS,
        m_axi_gmem_0_ARREGION,
        m_axi_gmem_0_ARUSER,
        m_axi_gmem_0_RVALID,
        m_axi_gmem_0_RREADY,
        m_axi_gmem_0_RDATA,
        m_axi_gmem_0_RLAST,
        m_axi_gmem_0_RID,
        m_axi_gmem_0_RFIFONUM,
        m_axi_gmem_0_RUSER,
        m_axi_gmem_0_RRESP,
        m_axi_gmem_0_BVALID,
        m_axi_gmem_0_BREADY,
        m_axi_gmem_0_BRESP,
        m_axi_gmem_0_BID,
        m_axi_gmem_0_BUSER,
        empty_17,
        mul_ln45_1,
        sp_in_fm_address0,
        sp_in_fm_ce0,
        sp_in_fm_we0,
        sp_in_fm_d0,
        sp_in_fm_1_address0,
        sp_in_fm_1_ce0,
        sp_in_fm_1_we0,
        sp_in_fm_1_d0,
        sp_in_fm_2_address0,
        sp_in_fm_2_ce0,
        sp_in_fm_2_we0,
        sp_in_fm_2_d0,
        sp_in_fm_3_address0,
        sp_in_fm_3_ce0,
        sp_in_fm_3_we0,
        sp_in_fm_3_d0,
        sp_in_fm_4_address0,
        sp_in_fm_4_ce0,
        sp_in_fm_4_we0,
        sp_in_fm_4_d0,
        sp_in_fm_5_address0,
        sp_in_fm_5_ce0,
        sp_in_fm_5_we0,
        sp_in_fm_5_d0,
        sp_in_fm_6_address0,
        sp_in_fm_6_ce0,
        sp_in_fm_6_we0,
        sp_in_fm_6_d0,
        sp_in_fm_7_address0,
        sp_in_fm_7_ce0,
        sp_in_fm_7_we0,
        sp_in_fm_7_d0,
        sp_in_fm_8_address0,
        sp_in_fm_8_ce0,
        sp_in_fm_8_we0,
        sp_in_fm_8_d0,
        sp_in_fm_9_address0,
        sp_in_fm_9_ce0,
        sp_in_fm_9_we0,
        sp_in_fm_9_d0,
        sp_in_fm_10_address0,
        sp_in_fm_10_ce0,
        sp_in_fm_10_we0,
        sp_in_fm_10_d0,
        sp_in_fm_11_address0,
        sp_in_fm_11_ce0,
        sp_in_fm_11_we0,
        sp_in_fm_11_d0,
        sp_in_fm_12_address0,
        sp_in_fm_12_ce0,
        sp_in_fm_12_we0,
        sp_in_fm_12_d0,
        sp_in_fm_13_address0,
        sp_in_fm_13_ce0,
        sp_in_fm_13_we0,
        sp_in_fm_13_d0,
        sp_in_fm_14_address0,
        sp_in_fm_14_ce0,
        sp_in_fm_14_we0,
        sp_in_fm_14_d0,
        sp_in_fm_15_address0,
        sp_in_fm_15_ce0,
        sp_in_fm_15_we0,
        sp_in_fm_15_d0,
        zext_ln40,
        mul_ln45,
        icmp_ln40,
        empty,
        read_w,
        cmd_in_total_channels,
        cmd_in_offset,
        sext_ln36_1,
        ddr_mem
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_0_AWVALID;
input   m_axi_gmem_0_AWREADY;
output  [63:0] m_axi_gmem_0_AWADDR;
output  [0:0] m_axi_gmem_0_AWID;
output  [31:0] m_axi_gmem_0_AWLEN;
output  [2:0] m_axi_gmem_0_AWSIZE;
output  [1:0] m_axi_gmem_0_AWBURST;
output  [1:0] m_axi_gmem_0_AWLOCK;
output  [3:0] m_axi_gmem_0_AWCACHE;
output  [2:0] m_axi_gmem_0_AWPROT;
output  [3:0] m_axi_gmem_0_AWQOS;
output  [3:0] m_axi_gmem_0_AWREGION;
output  [0:0] m_axi_gmem_0_AWUSER;
output   m_axi_gmem_0_WVALID;
input   m_axi_gmem_0_WREADY;
output  [15:0] m_axi_gmem_0_WDATA;
output  [1:0] m_axi_gmem_0_WSTRB;
output   m_axi_gmem_0_WLAST;
output  [0:0] m_axi_gmem_0_WID;
output  [0:0] m_axi_gmem_0_WUSER;
output   m_axi_gmem_0_ARVALID;
input   m_axi_gmem_0_ARREADY;
output  [63:0] m_axi_gmem_0_ARADDR;
output  [0:0] m_axi_gmem_0_ARID;
output  [31:0] m_axi_gmem_0_ARLEN;
output  [2:0] m_axi_gmem_0_ARSIZE;
output  [1:0] m_axi_gmem_0_ARBURST;
output  [1:0] m_axi_gmem_0_ARLOCK;
output  [3:0] m_axi_gmem_0_ARCACHE;
output  [2:0] m_axi_gmem_0_ARPROT;
output  [3:0] m_axi_gmem_0_ARQOS;
output  [3:0] m_axi_gmem_0_ARREGION;
output  [0:0] m_axi_gmem_0_ARUSER;
input   m_axi_gmem_0_RVALID;
output   m_axi_gmem_0_RREADY;
input  [15:0] m_axi_gmem_0_RDATA;
input   m_axi_gmem_0_RLAST;
input  [0:0] m_axi_gmem_0_RID;
input  [9:0] m_axi_gmem_0_RFIFONUM;
input  [0:0] m_axi_gmem_0_RUSER;
input  [1:0] m_axi_gmem_0_RRESP;
input   m_axi_gmem_0_BVALID;
output   m_axi_gmem_0_BREADY;
input  [1:0] m_axi_gmem_0_BRESP;
input  [0:0] m_axi_gmem_0_BID;
input  [0:0] m_axi_gmem_0_BUSER;
input  [31:0] empty_17;
input  [92:0] mul_ln45_1;
output  [11:0] sp_in_fm_address0;
output   sp_in_fm_ce0;
output   sp_in_fm_we0;
output  [15:0] sp_in_fm_d0;
output  [11:0] sp_in_fm_1_address0;
output   sp_in_fm_1_ce0;
output   sp_in_fm_1_we0;
output  [15:0] sp_in_fm_1_d0;
output  [11:0] sp_in_fm_2_address0;
output   sp_in_fm_2_ce0;
output   sp_in_fm_2_we0;
output  [15:0] sp_in_fm_2_d0;
output  [11:0] sp_in_fm_3_address0;
output   sp_in_fm_3_ce0;
output   sp_in_fm_3_we0;
output  [15:0] sp_in_fm_3_d0;
output  [11:0] sp_in_fm_4_address0;
output   sp_in_fm_4_ce0;
output   sp_in_fm_4_we0;
output  [15:0] sp_in_fm_4_d0;
output  [11:0] sp_in_fm_5_address0;
output   sp_in_fm_5_ce0;
output   sp_in_fm_5_we0;
output  [15:0] sp_in_fm_5_d0;
output  [11:0] sp_in_fm_6_address0;
output   sp_in_fm_6_ce0;
output   sp_in_fm_6_we0;
output  [15:0] sp_in_fm_6_d0;
output  [11:0] sp_in_fm_7_address0;
output   sp_in_fm_7_ce0;
output   sp_in_fm_7_we0;
output  [15:0] sp_in_fm_7_d0;
output  [11:0] sp_in_fm_8_address0;
output   sp_in_fm_8_ce0;
output   sp_in_fm_8_we0;
output  [15:0] sp_in_fm_8_d0;
output  [11:0] sp_in_fm_9_address0;
output   sp_in_fm_9_ce0;
output   sp_in_fm_9_we0;
output  [15:0] sp_in_fm_9_d0;
output  [11:0] sp_in_fm_10_address0;
output   sp_in_fm_10_ce0;
output   sp_in_fm_10_we0;
output  [15:0] sp_in_fm_10_d0;
output  [11:0] sp_in_fm_11_address0;
output   sp_in_fm_11_ce0;
output   sp_in_fm_11_we0;
output  [15:0] sp_in_fm_11_d0;
output  [11:0] sp_in_fm_12_address0;
output   sp_in_fm_12_ce0;
output   sp_in_fm_12_we0;
output  [15:0] sp_in_fm_12_d0;
output  [11:0] sp_in_fm_13_address0;
output   sp_in_fm_13_ce0;
output   sp_in_fm_13_we0;
output  [15:0] sp_in_fm_13_d0;
output  [11:0] sp_in_fm_14_address0;
output   sp_in_fm_14_ce0;
output   sp_in_fm_14_we0;
output  [15:0] sp_in_fm_14_d0;
output  [11:0] sp_in_fm_15_address0;
output   sp_in_fm_15_ce0;
output   sp_in_fm_15_we0;
output  [15:0] sp_in_fm_15_d0;
input  [30:0] zext_ln40;
input  [61:0] mul_ln45;
input  [0:0] icmp_ln40;
input  [0:0] empty;
input  [31:0] read_w;
input  [31:0] cmd_in_total_channels;
input  [31:0] cmd_in_offset;
input  [31:0] sext_ln36_1;
input  [63:0] ddr_mem;

reg ap_idle;
reg m_axi_gmem_0_ARVALID;
reg m_axi_gmem_0_RREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_idle_pp0;
reg   [0:0] first_iter_0_reg_991;
reg    ap_block_state4_io_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln36_fu_528_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_blk_n_R;
wire    ap_block_pp0_stage0_grp1;
reg    gmem_blk_n_AR;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001_grp1;
reg    ap_block_pp0_stage0_11001;
wire  signed [32:0] sext_ln36_1_cast_fu_485_p1;
reg  signed [32:0] sext_ln36_1_cast_reg_955;
wire   [63:0] mul_ln45_cast_fu_489_p1;
reg   [63:0] mul_ln45_cast_reg_960;
wire   [63:0] zext_ln40_cast_fu_493_p1;
reg   [63:0] zext_ln40_cast_reg_965;
reg   [0:0] icmp_ln36_reg_970;
wire   [0:0] icmp_ln38_fu_548_p2;
reg   [0:0] icmp_ln38_reg_974;
wire   [3:0] trunc_ln38_fu_561_p1;
reg   [3:0] trunc_ln38_reg_981;
wire   [31:0] mul_ln48_fu_477_p2;
reg   [31:0] mul_ln48_reg_986;
wire   [0:0] first_iter_0_fu_677_p2;
reg   [63:0] gmem_addr_reg_995;
wire   [3:0] trunc_ln40_fu_790_p1;
reg   [3:0] trunc_ln40_reg_1001;
reg   [3:0] trunc_ln40_reg_1001_pp0_iter3_reg;
reg   [3:0] trunc_ln40_reg_1001_pp0_iter4_reg;
reg   [3:0] trunc_ln40_reg_1001_pp0_iter5_reg;
reg   [3:0] trunc_ln40_reg_1001_pp0_iter6_reg;
reg   [3:0] trunc_ln40_reg_1001_pp0_iter7_reg;
reg   [3:0] trunc_ln40_reg_1001_pp0_iter8_reg;
reg   [3:0] trunc_ln40_reg_1001_pp0_iter9_reg;
reg   [3:0] trunc_ln40_reg_1001_pp0_iter10_reg;
reg   [3:0] trunc_ln40_reg_1001_pp0_iter11_reg;
wire   [11:0] add_ln49_1_fu_804_p2;
reg   [11:0] add_ln49_1_reg_1005;
reg   [11:0] add_ln49_1_reg_1005_pp0_iter3_reg;
reg   [11:0] add_ln49_1_reg_1005_pp0_iter4_reg;
reg   [11:0] add_ln49_1_reg_1005_pp0_iter5_reg;
reg   [11:0] add_ln49_1_reg_1005_pp0_iter6_reg;
reg   [11:0] add_ln49_1_reg_1005_pp0_iter7_reg;
reg   [11:0] add_ln49_1_reg_1005_pp0_iter8_reg;
reg   [11:0] add_ln49_1_reg_1005_pp0_iter9_reg;
reg   [11:0] add_ln49_1_reg_1005_pp0_iter10_reg;
reg   [11:0] add_ln49_1_reg_1005_pp0_iter11_reg;
reg   [15:0] gmem_addr_read_reg_1010;
reg    ap_condition_exit_pp0_iter2_stage0;
wire   [63:0] zext_ln49_fu_860_p1;
wire    ap_block_pp0_stage0_grp0;
wire  signed [63:0] sext_ln40_2_fu_755_p1;
reg   [30:0] ic_fu_172;
wire   [30:0] add_ln40_2_fu_844_p2;
wire    ap_loop_init;
reg   [30:0] c_fu_176;
wire   [30:0] select_ln38_1_fu_669_p3;
reg   [63:0] indvar_flatten_fu_180;
wire   [63:0] select_ln38_2_fu_597_p3;
wire    ap_block_pp0_stage0;
reg   [30:0] r_fu_184;
wire   [30:0] select_ln36_3_fu_553_p3;
reg   [92:0] indvar_flatten25_fu_188;
wire   [92:0] add_ln36_1_fu_533_p2;
reg    sp_in_fm_14_we0_local;
reg    sp_in_fm_14_ce0_local;
reg    sp_in_fm_13_we0_local;
reg    sp_in_fm_13_ce0_local;
reg    sp_in_fm_12_we0_local;
reg    sp_in_fm_12_ce0_local;
reg    sp_in_fm_11_we0_local;
reg    sp_in_fm_11_ce0_local;
reg    sp_in_fm_10_we0_local;
reg    sp_in_fm_10_ce0_local;
reg    sp_in_fm_9_we0_local;
reg    sp_in_fm_9_ce0_local;
reg    sp_in_fm_8_we0_local;
reg    sp_in_fm_8_ce0_local;
reg    sp_in_fm_7_we0_local;
reg    sp_in_fm_7_ce0_local;
reg    sp_in_fm_6_we0_local;
reg    sp_in_fm_6_ce0_local;
reg    sp_in_fm_5_we0_local;
reg    sp_in_fm_5_ce0_local;
reg    sp_in_fm_4_we0_local;
reg    sp_in_fm_4_ce0_local;
reg    sp_in_fm_3_we0_local;
reg    sp_in_fm_3_ce0_local;
reg    sp_in_fm_2_we0_local;
reg    sp_in_fm_2_ce0_local;
reg    sp_in_fm_1_we0_local;
reg    sp_in_fm_1_ce0_local;
reg    sp_in_fm_we0_local;
reg    sp_in_fm_ce0_local;
reg    sp_in_fm_15_we0_local;
reg    sp_in_fm_15_ce0_local;
wire   [30:0] mul_ln48_fu_477_p0;
wire  signed [31:0] mul_ln48_1_fu_481_p0;
wire   [30:0] add_ln36_fu_542_p2;
wire   [29:0] lshr_ln1_fu_565_p4;
wire   [30:0] zext_ln43_fu_575_p1;
wire   [30:0] read_r_fu_579_p3;
wire   [63:0] add_ln38_1_fu_591_p2;
wire   [31:0] zext_ln40_1_fu_623_p1;
wire   [0:0] icmp_ln40_1_fu_627_p2;
wire   [30:0] select_ln36_fu_635_p3;
wire   [0:0] select_ln36_2_fu_649_p3;
wire   [30:0] select_ln36_1_fu_642_p3;
wire   [30:0] add_ln38_fu_655_p2;
wire   [30:0] select_ln38_fu_661_p3;
wire   [29:0] lshr_ln2_fu_683_p4;
wire   [30:0] zext_ln44_fu_693_p1;
wire   [30:0] read_c_fu_697_p3;
wire   [31:0] zext_ln48_1_fu_704_p1;
wire   [31:0] mul_ln48_1_fu_481_p2;
wire   [31:0] add_ln48_1_fu_714_p2;
wire  signed [32:0] sext_ln40_fu_719_p1;
wire   [32:0] add_ln40_fu_723_p2;
wire   [33:0] tmp_5_fu_728_p3;
wire  signed [63:0] sext_ln40_1_fu_736_p1;
wire   [63:0] add_ln40_1_fu_740_p2;
wire   [62:0] trunc_ln3_fu_745_p4;
wire   [7:0] tmp_6_fu_765_p3;
wire   [7:0] trunc_ln49_fu_772_p1;
wire   [7:0] add_ln49_fu_776_p2;
wire   [11:0] tmp_4_fu_782_p3;
wire   [11:0] lshr_ln3_fu_794_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [31:0] mul_ln48_fu_477_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 ic_fu_172 = 31'd0;
#0 c_fu_176 = 31'd0;
#0 indvar_flatten_fu_180 = 64'd0;
#0 r_fu_184 = 31'd0;
#0 indvar_flatten25_fu_188 = 93'd0;
#0 ap_done_reg = 1'b0;
end

yolo_npu_v2_core_mul_31ns_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_31ns_32s_32_1_1_U36(
    .din0(mul_ln48_fu_477_p0),
    .din1(read_w),
    .dout(mul_ln48_fu_477_p2)
);

yolo_npu_v2_core_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U37(
    .din0(mul_ln48_1_fu_481_p0),
    .din1(cmd_in_total_channels),
    .dout(mul_ln48_1_fu_481_p2)
);

yolo_npu_v2_core_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter11_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter2_stage0)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            c_fu_176 <= 31'd0;
        end else if (((icmp_ln36_reg_970 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            c_fu_176 <= select_ln38_1_fu_669_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ic_fu_172 <= 31'd0;
        end else if (((icmp_ln36_reg_970 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ic_fu_172 <= add_ln40_2_fu_844_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten25_fu_188 <= 93'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln36_fu_528_p2 == 1'd0))) begin
            indvar_flatten25_fu_188 <= add_ln36_1_fu_533_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_180 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln36_fu_528_p2 == 1'd0))) begin
            indvar_flatten_fu_180 <= select_ln38_2_fu_597_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            r_fu_184 <= 31'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln36_fu_528_p2 == 1'd0))) begin
            r_fu_184 <= select_ln36_3_fu_553_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        add_ln49_1_reg_1005 <= add_ln49_1_fu_804_p2;
        add_ln49_1_reg_1005_pp0_iter10_reg <= add_ln49_1_reg_1005_pp0_iter9_reg;
        add_ln49_1_reg_1005_pp0_iter11_reg <= add_ln49_1_reg_1005_pp0_iter10_reg;
        add_ln49_1_reg_1005_pp0_iter3_reg <= add_ln49_1_reg_1005;
        add_ln49_1_reg_1005_pp0_iter4_reg <= add_ln49_1_reg_1005_pp0_iter3_reg;
        add_ln49_1_reg_1005_pp0_iter5_reg <= add_ln49_1_reg_1005_pp0_iter4_reg;
        add_ln49_1_reg_1005_pp0_iter6_reg <= add_ln49_1_reg_1005_pp0_iter5_reg;
        add_ln49_1_reg_1005_pp0_iter7_reg <= add_ln49_1_reg_1005_pp0_iter6_reg;
        add_ln49_1_reg_1005_pp0_iter8_reg <= add_ln49_1_reg_1005_pp0_iter7_reg;
        add_ln49_1_reg_1005_pp0_iter9_reg <= add_ln49_1_reg_1005_pp0_iter8_reg;
        first_iter_0_reg_991 <= first_iter_0_fu_677_p2;
        gmem_addr_read_reg_1010 <= m_axi_gmem_0_RDATA;
        gmem_addr_reg_995 <= sext_ln40_2_fu_755_p1;
        trunc_ln40_reg_1001 <= trunc_ln40_fu_790_p1;
        trunc_ln40_reg_1001_pp0_iter10_reg <= trunc_ln40_reg_1001_pp0_iter9_reg;
        trunc_ln40_reg_1001_pp0_iter11_reg <= trunc_ln40_reg_1001_pp0_iter10_reg;
        trunc_ln40_reg_1001_pp0_iter3_reg <= trunc_ln40_reg_1001;
        trunc_ln40_reg_1001_pp0_iter4_reg <= trunc_ln40_reg_1001_pp0_iter3_reg;
        trunc_ln40_reg_1001_pp0_iter5_reg <= trunc_ln40_reg_1001_pp0_iter4_reg;
        trunc_ln40_reg_1001_pp0_iter6_reg <= trunc_ln40_reg_1001_pp0_iter5_reg;
        trunc_ln40_reg_1001_pp0_iter7_reg <= trunc_ln40_reg_1001_pp0_iter6_reg;
        trunc_ln40_reg_1001_pp0_iter8_reg <= trunc_ln40_reg_1001_pp0_iter7_reg;
        trunc_ln40_reg_1001_pp0_iter9_reg <= trunc_ln40_reg_1001_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln36_reg_970 <= icmp_ln36_fu_528_p2;
        icmp_ln38_reg_974 <= icmp_ln38_fu_548_p2;
        mul_ln45_cast_reg_960[61 : 0] <= mul_ln45_cast_fu_489_p1[61 : 0];
        mul_ln48_reg_986 <= mul_ln48_fu_477_p2;
        trunc_ln38_reg_981 <= trunc_ln38_fu_561_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        sext_ln36_1_cast_reg_955 <= sext_ln36_1_cast_fu_485_p1;
        zext_ln40_cast_reg_965[30 : 0] <= zext_ln40_cast_fu_493_p1[30 : 0];
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln36_fu_528_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln36_reg_970 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter11_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1) & (first_iter_0_reg_991 == 1'd1))) begin
        gmem_blk_n_AR = m_axi_gmem_0_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        gmem_blk_n_R = m_axi_gmem_0_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (first_iter_0_reg_991 == 1'd1))) begin
        m_axi_gmem_0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m_axi_gmem_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_in_fm_10_ce0_local = 1'b1;
    end else begin
        sp_in_fm_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (trunc_ln40_reg_1001_pp0_iter11_reg == 4'd10) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_in_fm_10_we0_local = 1'b1;
    end else begin
        sp_in_fm_10_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_in_fm_11_ce0_local = 1'b1;
    end else begin
        sp_in_fm_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (trunc_ln40_reg_1001_pp0_iter11_reg == 4'd11) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_in_fm_11_we0_local = 1'b1;
    end else begin
        sp_in_fm_11_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_in_fm_12_ce0_local = 1'b1;
    end else begin
        sp_in_fm_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (trunc_ln40_reg_1001_pp0_iter11_reg == 4'd12) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_in_fm_12_we0_local = 1'b1;
    end else begin
        sp_in_fm_12_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_in_fm_13_ce0_local = 1'b1;
    end else begin
        sp_in_fm_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (trunc_ln40_reg_1001_pp0_iter11_reg == 4'd13) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_in_fm_13_we0_local = 1'b1;
    end else begin
        sp_in_fm_13_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_in_fm_14_ce0_local = 1'b1;
    end else begin
        sp_in_fm_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (trunc_ln40_reg_1001_pp0_iter11_reg == 4'd14) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_in_fm_14_we0_local = 1'b1;
    end else begin
        sp_in_fm_14_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_in_fm_15_ce0_local = 1'b1;
    end else begin
        sp_in_fm_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (trunc_ln40_reg_1001_pp0_iter11_reg == 4'd15) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_in_fm_15_we0_local = 1'b1;
    end else begin
        sp_in_fm_15_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_in_fm_1_ce0_local = 1'b1;
    end else begin
        sp_in_fm_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (trunc_ln40_reg_1001_pp0_iter11_reg == 4'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_in_fm_1_we0_local = 1'b1;
    end else begin
        sp_in_fm_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_in_fm_2_ce0_local = 1'b1;
    end else begin
        sp_in_fm_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (trunc_ln40_reg_1001_pp0_iter11_reg == 4'd2) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_in_fm_2_we0_local = 1'b1;
    end else begin
        sp_in_fm_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_in_fm_3_ce0_local = 1'b1;
    end else begin
        sp_in_fm_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (trunc_ln40_reg_1001_pp0_iter11_reg == 4'd3) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_in_fm_3_we0_local = 1'b1;
    end else begin
        sp_in_fm_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_in_fm_4_ce0_local = 1'b1;
    end else begin
        sp_in_fm_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (trunc_ln40_reg_1001_pp0_iter11_reg == 4'd4) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_in_fm_4_we0_local = 1'b1;
    end else begin
        sp_in_fm_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_in_fm_5_ce0_local = 1'b1;
    end else begin
        sp_in_fm_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (trunc_ln40_reg_1001_pp0_iter11_reg == 4'd5) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_in_fm_5_we0_local = 1'b1;
    end else begin
        sp_in_fm_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_in_fm_6_ce0_local = 1'b1;
    end else begin
        sp_in_fm_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (trunc_ln40_reg_1001_pp0_iter11_reg == 4'd6) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_in_fm_6_we0_local = 1'b1;
    end else begin
        sp_in_fm_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_in_fm_7_ce0_local = 1'b1;
    end else begin
        sp_in_fm_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (trunc_ln40_reg_1001_pp0_iter11_reg == 4'd7) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_in_fm_7_we0_local = 1'b1;
    end else begin
        sp_in_fm_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_in_fm_8_ce0_local = 1'b1;
    end else begin
        sp_in_fm_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (trunc_ln40_reg_1001_pp0_iter11_reg == 4'd8) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_in_fm_8_we0_local = 1'b1;
    end else begin
        sp_in_fm_8_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_in_fm_9_ce0_local = 1'b1;
    end else begin
        sp_in_fm_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (trunc_ln40_reg_1001_pp0_iter11_reg == 4'd9) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_in_fm_9_we0_local = 1'b1;
    end else begin
        sp_in_fm_9_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_in_fm_ce0_local = 1'b1;
    end else begin
        sp_in_fm_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (trunc_ln40_reg_1001_pp0_iter11_reg == 4'd0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_in_fm_we0_local = 1'b1;
    end else begin
        sp_in_fm_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln36_1_fu_533_p2 = (indvar_flatten25_fu_188 + 93'd1);

assign add_ln36_fu_542_p2 = (r_fu_184 + 31'd1);

assign add_ln38_1_fu_591_p2 = (indvar_flatten_fu_180 + 64'd1);

assign add_ln38_fu_655_p2 = (select_ln36_fu_635_p3 + 31'd1);

assign add_ln40_1_fu_740_p2 = ($signed(sext_ln40_1_fu_736_p1) + $signed(ddr_mem));

assign add_ln40_2_fu_844_p2 = (select_ln38_fu_661_p3 + 31'd1);

assign add_ln40_fu_723_p2 = ($signed(sext_ln40_fu_719_p1) + $signed(sext_ln36_1_cast_reg_955));

assign add_ln48_1_fu_714_p2 = (mul_ln48_1_fu_481_p2 + cmd_in_offset);

assign add_ln49_1_fu_804_p2 = (tmp_4_fu_782_p3 + lshr_ln3_fu_794_p4);

assign add_ln49_fu_776_p2 = (tmp_6_fu_765_p3 + trunc_ln49_fu_772_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter11 == 1'b1) & (m_axi_gmem_0_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_io_grp1)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((ap_enable_reg_pp0_iter11 == 1'b1) & (m_axi_gmem_0_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_io_grp1)));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter11 == 1'b1) & (m_axi_gmem_0_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_io_grp1)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_io_grp1 = ((m_axi_gmem_0_ARREADY == 1'b0) & (first_iter_0_reg_991 == 1'd1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign first_iter_0_fu_677_p2 = ((select_ln38_fu_661_p3 == 31'd0) ? 1'b1 : 1'b0);

assign icmp_ln36_fu_528_p2 = ((indvar_flatten25_fu_188 == mul_ln45_1) ? 1'b1 : 1'b0);

assign icmp_ln38_fu_548_p2 = ((indvar_flatten_fu_180 == mul_ln45_cast_reg_960) ? 1'b1 : 1'b0);

assign icmp_ln40_1_fu_627_p2 = (($signed(zext_ln40_1_fu_623_p1) < $signed(empty_17)) ? 1'b1 : 1'b0);

assign lshr_ln1_fu_565_p4 = {{select_ln36_3_fu_553_p3[30:1]}};

assign lshr_ln2_fu_683_p4 = {{select_ln38_1_fu_669_p3[30:1]}};

assign lshr_ln3_fu_794_p4 = {{select_ln38_fu_661_p3[15:4]}};

assign m_axi_gmem_0_ARADDR = gmem_addr_reg_995;

assign m_axi_gmem_0_ARBURST = 2'd0;

assign m_axi_gmem_0_ARCACHE = 4'd0;

assign m_axi_gmem_0_ARID = 1'd0;

assign m_axi_gmem_0_ARLEN = zext_ln40_cast_reg_965;

assign m_axi_gmem_0_ARLOCK = 2'd0;

assign m_axi_gmem_0_ARPROT = 3'd0;

assign m_axi_gmem_0_ARQOS = 4'd0;

assign m_axi_gmem_0_ARREGION = 4'd0;

assign m_axi_gmem_0_ARSIZE = 3'd0;

assign m_axi_gmem_0_ARUSER = 1'd0;

assign m_axi_gmem_0_AWADDR = 64'd0;

assign m_axi_gmem_0_AWBURST = 2'd0;

assign m_axi_gmem_0_AWCACHE = 4'd0;

assign m_axi_gmem_0_AWID = 1'd0;

assign m_axi_gmem_0_AWLEN = 32'd0;

assign m_axi_gmem_0_AWLOCK = 2'd0;

assign m_axi_gmem_0_AWPROT = 3'd0;

assign m_axi_gmem_0_AWQOS = 4'd0;

assign m_axi_gmem_0_AWREGION = 4'd0;

assign m_axi_gmem_0_AWSIZE = 3'd0;

assign m_axi_gmem_0_AWUSER = 1'd0;

assign m_axi_gmem_0_AWVALID = 1'b0;

assign m_axi_gmem_0_BREADY = 1'b0;

assign m_axi_gmem_0_WDATA = 16'd0;

assign m_axi_gmem_0_WID = 1'd0;

assign m_axi_gmem_0_WLAST = 1'b0;

assign m_axi_gmem_0_WSTRB = 2'd0;

assign m_axi_gmem_0_WUSER = 1'd0;

assign m_axi_gmem_0_WVALID = 1'b0;

assign mul_ln45_cast_fu_489_p1 = mul_ln45;

assign mul_ln48_1_fu_481_p0 = (zext_ln48_1_fu_704_p1 + mul_ln48_reg_986);

assign mul_ln48_fu_477_p0 = mul_ln48_fu_477_p00;

assign mul_ln48_fu_477_p00 = read_r_fu_579_p3;

assign read_c_fu_697_p3 = ((empty[0:0] == 1'b1) ? zext_ln44_fu_693_p1 : select_ln38_1_fu_669_p3);

assign read_r_fu_579_p3 = ((empty[0:0] == 1'b1) ? zext_ln43_fu_575_p1 : select_ln36_3_fu_553_p3);

assign select_ln36_1_fu_642_p3 = ((icmp_ln38_reg_974[0:0] == 1'b1) ? 31'd0 : ic_fu_172);

assign select_ln36_2_fu_649_p3 = ((icmp_ln38_reg_974[0:0] == 1'b1) ? icmp_ln40 : icmp_ln40_1_fu_627_p2);

assign select_ln36_3_fu_553_p3 = ((icmp_ln38_fu_548_p2[0:0] == 1'b1) ? add_ln36_fu_542_p2 : r_fu_184);

assign select_ln36_fu_635_p3 = ((icmp_ln38_reg_974[0:0] == 1'b1) ? 31'd0 : c_fu_176);

assign select_ln38_1_fu_669_p3 = ((select_ln36_2_fu_649_p3[0:0] == 1'b1) ? select_ln36_fu_635_p3 : add_ln38_fu_655_p2);

assign select_ln38_2_fu_597_p3 = ((icmp_ln38_fu_548_p2[0:0] == 1'b1) ? 64'd1 : add_ln38_1_fu_591_p2);

assign select_ln38_fu_661_p3 = ((select_ln36_2_fu_649_p3[0:0] == 1'b1) ? select_ln36_1_fu_642_p3 : 31'd0);

assign sext_ln36_1_cast_fu_485_p1 = $signed(sext_ln36_1);

assign sext_ln40_1_fu_736_p1 = $signed(tmp_5_fu_728_p3);

assign sext_ln40_2_fu_755_p1 = $signed(trunc_ln3_fu_745_p4);

assign sext_ln40_fu_719_p1 = $signed(add_ln48_1_fu_714_p2);

assign sp_in_fm_10_address0 = zext_ln49_fu_860_p1;

assign sp_in_fm_10_ce0 = sp_in_fm_10_ce0_local;

assign sp_in_fm_10_d0 = gmem_addr_read_reg_1010;

assign sp_in_fm_10_we0 = sp_in_fm_10_we0_local;

assign sp_in_fm_11_address0 = zext_ln49_fu_860_p1;

assign sp_in_fm_11_ce0 = sp_in_fm_11_ce0_local;

assign sp_in_fm_11_d0 = gmem_addr_read_reg_1010;

assign sp_in_fm_11_we0 = sp_in_fm_11_we0_local;

assign sp_in_fm_12_address0 = zext_ln49_fu_860_p1;

assign sp_in_fm_12_ce0 = sp_in_fm_12_ce0_local;

assign sp_in_fm_12_d0 = gmem_addr_read_reg_1010;

assign sp_in_fm_12_we0 = sp_in_fm_12_we0_local;

assign sp_in_fm_13_address0 = zext_ln49_fu_860_p1;

assign sp_in_fm_13_ce0 = sp_in_fm_13_ce0_local;

assign sp_in_fm_13_d0 = gmem_addr_read_reg_1010;

assign sp_in_fm_13_we0 = sp_in_fm_13_we0_local;

assign sp_in_fm_14_address0 = zext_ln49_fu_860_p1;

assign sp_in_fm_14_ce0 = sp_in_fm_14_ce0_local;

assign sp_in_fm_14_d0 = gmem_addr_read_reg_1010;

assign sp_in_fm_14_we0 = sp_in_fm_14_we0_local;

assign sp_in_fm_15_address0 = zext_ln49_fu_860_p1;

assign sp_in_fm_15_ce0 = sp_in_fm_15_ce0_local;

assign sp_in_fm_15_d0 = gmem_addr_read_reg_1010;

assign sp_in_fm_15_we0 = sp_in_fm_15_we0_local;

assign sp_in_fm_1_address0 = zext_ln49_fu_860_p1;

assign sp_in_fm_1_ce0 = sp_in_fm_1_ce0_local;

assign sp_in_fm_1_d0 = gmem_addr_read_reg_1010;

assign sp_in_fm_1_we0 = sp_in_fm_1_we0_local;

assign sp_in_fm_2_address0 = zext_ln49_fu_860_p1;

assign sp_in_fm_2_ce0 = sp_in_fm_2_ce0_local;

assign sp_in_fm_2_d0 = gmem_addr_read_reg_1010;

assign sp_in_fm_2_we0 = sp_in_fm_2_we0_local;

assign sp_in_fm_3_address0 = zext_ln49_fu_860_p1;

assign sp_in_fm_3_ce0 = sp_in_fm_3_ce0_local;

assign sp_in_fm_3_d0 = gmem_addr_read_reg_1010;

assign sp_in_fm_3_we0 = sp_in_fm_3_we0_local;

assign sp_in_fm_4_address0 = zext_ln49_fu_860_p1;

assign sp_in_fm_4_ce0 = sp_in_fm_4_ce0_local;

assign sp_in_fm_4_d0 = gmem_addr_read_reg_1010;

assign sp_in_fm_4_we0 = sp_in_fm_4_we0_local;

assign sp_in_fm_5_address0 = zext_ln49_fu_860_p1;

assign sp_in_fm_5_ce0 = sp_in_fm_5_ce0_local;

assign sp_in_fm_5_d0 = gmem_addr_read_reg_1010;

assign sp_in_fm_5_we0 = sp_in_fm_5_we0_local;

assign sp_in_fm_6_address0 = zext_ln49_fu_860_p1;

assign sp_in_fm_6_ce0 = sp_in_fm_6_ce0_local;

assign sp_in_fm_6_d0 = gmem_addr_read_reg_1010;

assign sp_in_fm_6_we0 = sp_in_fm_6_we0_local;

assign sp_in_fm_7_address0 = zext_ln49_fu_860_p1;

assign sp_in_fm_7_ce0 = sp_in_fm_7_ce0_local;

assign sp_in_fm_7_d0 = gmem_addr_read_reg_1010;

assign sp_in_fm_7_we0 = sp_in_fm_7_we0_local;

assign sp_in_fm_8_address0 = zext_ln49_fu_860_p1;

assign sp_in_fm_8_ce0 = sp_in_fm_8_ce0_local;

assign sp_in_fm_8_d0 = gmem_addr_read_reg_1010;

assign sp_in_fm_8_we0 = sp_in_fm_8_we0_local;

assign sp_in_fm_9_address0 = zext_ln49_fu_860_p1;

assign sp_in_fm_9_ce0 = sp_in_fm_9_ce0_local;

assign sp_in_fm_9_d0 = gmem_addr_read_reg_1010;

assign sp_in_fm_9_we0 = sp_in_fm_9_we0_local;

assign sp_in_fm_address0 = zext_ln49_fu_860_p1;

assign sp_in_fm_ce0 = sp_in_fm_ce0_local;

assign sp_in_fm_d0 = gmem_addr_read_reg_1010;

assign sp_in_fm_we0 = sp_in_fm_we0_local;

assign tmp_4_fu_782_p3 = {{add_ln49_fu_776_p2}, {4'd0}};

assign tmp_5_fu_728_p3 = {{add_ln40_fu_723_p2}, {1'd0}};

assign tmp_6_fu_765_p3 = {{trunc_ln38_reg_981}, {4'd0}};

assign trunc_ln38_fu_561_p1 = select_ln36_3_fu_553_p3[3:0];

assign trunc_ln3_fu_745_p4 = {{add_ln40_1_fu_740_p2[63:1]}};

assign trunc_ln40_fu_790_p1 = select_ln38_fu_661_p3[3:0];

assign trunc_ln49_fu_772_p1 = select_ln38_1_fu_669_p3[7:0];

assign zext_ln40_1_fu_623_p1 = ic_fu_172;

assign zext_ln40_cast_fu_493_p1 = zext_ln40;

assign zext_ln43_fu_575_p1 = lshr_ln1_fu_565_p4;

assign zext_ln44_fu_693_p1 = lshr_ln2_fu_683_p4;

assign zext_ln48_1_fu_704_p1 = read_c_fu_697_p3;

assign zext_ln49_fu_860_p1 = add_ln49_1_reg_1005_pp0_iter11_reg;

always @ (posedge ap_clk) begin
    mul_ln45_cast_reg_960[63:62] <= 2'b00;
    zext_ln40_cast_reg_965[63:31] <= 33'b000000000000000000000000000000000;
end

endmodule //yolo_npu_v2_core_yolo_npu_v2_core_Pipeline_VITIS_LOOP_36_2_VITIS_LOOP_38_3_VITIS_LOOP_40_4
