[hls]
relative_roots=/home/dlohchab/projects/Verilog/DVCON/task_detection_tpu/yolo_backbone_v4
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=conv_layer_2/VITIS_LOOP_96_1 
syn.directive.pipeline=conv_layer_1/VITIS_LOOP_18_1 
# Inferred from performance & pipeline pragmas/directives
syn.directive.loop_flatten=conv_layer_1/VITIS_LOOP_24_7 off
syn.directive.loop_flatten=split_and_crop/VITIS_LOOP_69_1  
syn.directive.loop_flatten=conv_layer_2/VITIS_LOOP_102_7 off
syn.directive.loop_flatten=conv_layer_2/VITIS_LOOP_122_10  
syn.directive.loop_flatten=max_pool_2x2/VITIS_LOOP_175_1  


