set SynModuleInfo {
  {SRCNAME entry_proc MODELNAME entry_proc RTLNAME task_detection_accel_entry_proc}
  {SRCNAME Loop_VITIS_LOOP_402_1_proc MODELNAME Loop_VITIS_LOOP_402_1_proc RTLNAME task_detection_accel_Loop_VITIS_LOOP_402_1_proc
    SUBMODULES {
      {MODELNAME task_detection_accel_fpext_32ns_64_2_no_dsp_1 RTLNAME task_detection_accel_fpext_32ns_64_2_no_dsp_1 BINDTYPE op TYPE fpext IMPL auto LATENCY 1 ALLOW_PRAGMA 1}
      {MODELNAME task_detection_accel_sparsemux_9_3_16_1_1 RTLNAME task_detection_accel_sparsemux_9_3_16_1_1 BINDTYPE op TYPE sparsemux IMPL onehotencoding_realdef}
      {MODELNAME task_detection_accel_flow_control_loop_pipe RTLNAME task_detection_accel_flow_control_loop_pipe BINDTYPE interface TYPE internal_upc_flow_control INSTNAME task_detection_accel_flow_control_loop_pipe_U}
    }
  }
  {SRCNAME tpu_layer_1_Pipeline_VITIS_LOOP_56_1 MODELNAME tpu_layer_1_Pipeline_VITIS_LOOP_56_1 RTLNAME task_detection_accel_tpu_layer_1_Pipeline_VITIS_LOOP_56_1
    SUBMODULES {
      {MODELNAME task_detection_accel_flow_control_loop_pipe_sequential_init RTLNAME task_detection_accel_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME task_detection_accel_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME tpu_layer_1_Pipeline_VITIS_LOOP_75_3 MODELNAME tpu_layer_1_Pipeline_VITIS_LOOP_75_3 RTLNAME task_detection_accel_tpu_layer_1_Pipeline_VITIS_LOOP_75_3}
  {SRCNAME tpu_layer_1_Pipeline_VITIS_LOOP_76_4_VITIS_LOOP_77_5_VITIS_LOOP_78_6_VITIS_LOOP_ MODELNAME tpu_layer_1_Pipeline_VITIS_LOOP_76_4_VITIS_LOOP_77_5_VITIS_LOOP_78_6_VITIS_LOOP_s RTLNAME task_detection_accel_tpu_layer_1_Pipeline_VITIS_LOOP_76_4_VITIS_LOOP_77_5_VITIS_LOOP_78_6_VITIS_LOOP_s
    SUBMODULES {
      {MODELNAME task_detection_accel_mac_muladd_5ns_2ns_5ns_7_4_1 RTLNAME task_detection_accel_mac_muladd_5ns_2ns_5ns_7_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3}
    }
  }
  {SRCNAME run_mac_tile<0>_Pipeline_PUMP_LOOP MODELNAME run_mac_tile_0_Pipeline_PUMP_LOOP RTLNAME task_detection_accel_run_mac_tile_0_Pipeline_PUMP_LOOP
    SUBMODULES {
      {MODELNAME task_detection_accel_sparsemux_17_4_4_1_1 RTLNAME task_detection_accel_sparsemux_17_4_4_1_1 BINDTYPE op TYPE sparsemux IMPL compactencoding_dontcare}
      {MODELNAME task_detection_accel_sparsemux_17_4_16_1_1 RTLNAME task_detection_accel_sparsemux_17_4_16_1_1 BINDTYPE op TYPE sparsemux IMPL compactencoding_dontcare}
      {MODELNAME task_detection_accel_mac_muladd_16s_4ns_26s_26_4_1 RTLNAME task_detection_accel_mac_muladd_16s_4ns_26s_26_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3}
    }
  }
  {SRCNAME run_mac_tile<0> MODELNAME run_mac_tile_0_s RTLNAME task_detection_accel_run_mac_tile_0_s}
  {SRCNAME run_mac_tile<1>_Pipeline_PUMP_LOOP MODELNAME run_mac_tile_1_Pipeline_PUMP_LOOP RTLNAME task_detection_accel_run_mac_tile_1_Pipeline_PUMP_LOOP}
  {SRCNAME run_mac_tile<1> MODELNAME run_mac_tile_1_s RTLNAME task_detection_accel_run_mac_tile_1_s}
  {SRCNAME run_mac_tile<2>_Pipeline_PUMP_LOOP MODELNAME run_mac_tile_2_Pipeline_PUMP_LOOP RTLNAME task_detection_accel_run_mac_tile_2_Pipeline_PUMP_LOOP}
  {SRCNAME run_mac_tile<2> MODELNAME run_mac_tile_2_s RTLNAME task_detection_accel_run_mac_tile_2_s}
  {SRCNAME run_mac_tile<3>_Pipeline_PUMP_LOOP MODELNAME run_mac_tile_3_Pipeline_PUMP_LOOP RTLNAME task_detection_accel_run_mac_tile_3_Pipeline_PUMP_LOOP}
  {SRCNAME run_mac_tile<3> MODELNAME run_mac_tile_3_s RTLNAME task_detection_accel_run_mac_tile_3_s}
  {SRCNAME run_mac_tile<4>_Pipeline_PUMP_LOOP MODELNAME run_mac_tile_4_Pipeline_PUMP_LOOP RTLNAME task_detection_accel_run_mac_tile_4_Pipeline_PUMP_LOOP}
  {SRCNAME run_mac_tile<4> MODELNAME run_mac_tile_4_s RTLNAME task_detection_accel_run_mac_tile_4_s}
  {SRCNAME run_mac_tile<5>_Pipeline_PUMP_LOOP MODELNAME run_mac_tile_5_Pipeline_PUMP_LOOP RTLNAME task_detection_accel_run_mac_tile_5_Pipeline_PUMP_LOOP}
  {SRCNAME run_mac_tile<5> MODELNAME run_mac_tile_5_s RTLNAME task_detection_accel_run_mac_tile_5_s}
  {SRCNAME run_mac_tile<6>_Pipeline_PUMP_LOOP MODELNAME run_mac_tile_6_Pipeline_PUMP_LOOP RTLNAME task_detection_accel_run_mac_tile_6_Pipeline_PUMP_LOOP}
  {SRCNAME run_mac_tile<6> MODELNAME run_mac_tile_6_s RTLNAME task_detection_accel_run_mac_tile_6_s}
  {SRCNAME run_mac_tile<7>_Pipeline_PUMP_LOOP MODELNAME run_mac_tile_7_Pipeline_PUMP_LOOP RTLNAME task_detection_accel_run_mac_tile_7_Pipeline_PUMP_LOOP}
  {SRCNAME run_mac_tile<7> MODELNAME run_mac_tile_7_s RTLNAME task_detection_accel_run_mac_tile_7_s}
  {SRCNAME tpu_layer_1_Pipeline_VITIS_LOOP_123_12 MODELNAME tpu_layer_1_Pipeline_VITIS_LOOP_123_12 RTLNAME task_detection_accel_tpu_layer_1_Pipeline_VITIS_LOOP_123_12
    SUBMODULES {
      {MODELNAME task_detection_accel_sparsemux_17_3_16_1_1 RTLNAME task_detection_accel_sparsemux_17_3_16_1_1 BINDTYPE op TYPE sparsemux IMPL compactencoding_dontcare}
      {MODELNAME task_detection_accel_sparsemux_17_3_1_1_1 RTLNAME task_detection_accel_sparsemux_17_3_1_1_1 BINDTYPE op TYPE sparsemux IMPL compactencoding_dontcare}
    }
  }
  {SRCNAME tpu_layer_1_Pipeline_VITIS_LOOP_127_13 MODELNAME tpu_layer_1_Pipeline_VITIS_LOOP_127_13 RTLNAME task_detection_accel_tpu_layer_1_Pipeline_VITIS_LOOP_127_13}
  {SRCNAME tpu_layer_1_Pipeline_VITIS_LOOP_131_14 MODELNAME tpu_layer_1_Pipeline_VITIS_LOOP_131_14 RTLNAME task_detection_accel_tpu_layer_1_Pipeline_VITIS_LOOP_131_14}
  {SRCNAME tpu_layer_1_Pipeline_VITIS_LOOP_135_15 MODELNAME tpu_layer_1_Pipeline_VITIS_LOOP_135_15 RTLNAME task_detection_accel_tpu_layer_1_Pipeline_VITIS_LOOP_135_15}
  {SRCNAME tpu_layer_1_Pipeline_VITIS_LOOP_139_16 MODELNAME tpu_layer_1_Pipeline_VITIS_LOOP_139_16 RTLNAME task_detection_accel_tpu_layer_1_Pipeline_VITIS_LOOP_139_16}
  {SRCNAME tpu_layer_1_Pipeline_VITIS_LOOP_143_17 MODELNAME tpu_layer_1_Pipeline_VITIS_LOOP_143_17 RTLNAME task_detection_accel_tpu_layer_1_Pipeline_VITIS_LOOP_143_17}
  {SRCNAME tpu_layer_1_Pipeline_VITIS_LOOP_147_18 MODELNAME tpu_layer_1_Pipeline_VITIS_LOOP_147_18 RTLNAME task_detection_accel_tpu_layer_1_Pipeline_VITIS_LOOP_147_18}
  {SRCNAME tpu_layer_1_Pipeline_VITIS_LOOP_151_19 MODELNAME tpu_layer_1_Pipeline_VITIS_LOOP_151_19 RTLNAME task_detection_accel_tpu_layer_1_Pipeline_VITIS_LOOP_151_19}
  {SRCNAME tpu_layer_1 MODELNAME tpu_layer_1 RTLNAME task_detection_accel_tpu_layer_1
    SUBMODULES {
      {MODELNAME task_detection_accel_mul_2ns_6ns_7_1_1 RTLNAME task_detection_accel_mul_2ns_6ns_7_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME task_detection_accel_tpu_layer_1_tpu_layer_1_stream_ap_fixed_0_stream_ap_fixed_16_6_5_3_0_0_bias_7bkb RTLNAME task_detection_accel_tpu_layer_1_tpu_layer_1_stream_ap_fixed_0_stream_ap_fixed_16_6_5_3_0_0_bias_7bkb BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME task_detection_accel_tpu_layer_1_p_ZZ11tpu_layer_1RN3hls6streamI8ap_fixedILi16ELi6EL9ap_q_mode5EL9jbC RTLNAME task_detection_accel_tpu_layer_1_p_ZZ11tpu_layer_1RN3hls6streamI8ap_fixedILi16ELi6EL9ap_q_mode5EL9jbC BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME task_detection_accel_tpu_layer_1_x_padded_RAM_AUTO_1R1W RTLNAME task_detection_accel_tpu_layer_1_x_padded_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME tpu_layer_2_Pipeline_VITIS_LOOP_165_1 MODELNAME tpu_layer_2_Pipeline_VITIS_LOOP_165_1 RTLNAME task_detection_accel_tpu_layer_2_Pipeline_VITIS_LOOP_165_1}
  {SRCNAME tpu_layer_2_Pipeline_VITIS_LOOP_180_2 MODELNAME tpu_layer_2_Pipeline_VITIS_LOOP_180_2 RTLNAME task_detection_accel_tpu_layer_2_Pipeline_VITIS_LOOP_180_2}
  {SRCNAME tpu_layer_2_Pipeline_VITIS_LOOP_181_3_VITIS_LOOP_182_4_VITIS_LOOP_183_5_VITIS_LO MODELNAME tpu_layer_2_Pipeline_VITIS_LOOP_181_3_VITIS_LOOP_182_4_VITIS_LOOP_183_5_VITIS_LO RTLNAME task_detection_accel_tpu_layer_2_Pipeline_VITIS_LOOP_181_3_VITIS_LOOP_182_4_VITIS_LOOP_183_5_VITIS_LO}
  {SRCNAME tpu_layer_2_Pipeline_VITIS_LOOP_226_11 MODELNAME tpu_layer_2_Pipeline_VITIS_LOOP_226_11 RTLNAME task_detection_accel_tpu_layer_2_Pipeline_VITIS_LOOP_226_11}
  {SRCNAME tpu_layer_2_Pipeline_VITIS_LOOP_230_12 MODELNAME tpu_layer_2_Pipeline_VITIS_LOOP_230_12 RTLNAME task_detection_accel_tpu_layer_2_Pipeline_VITIS_LOOP_230_12}
  {SRCNAME tpu_layer_2_Pipeline_VITIS_LOOP_234_13 MODELNAME tpu_layer_2_Pipeline_VITIS_LOOP_234_13 RTLNAME task_detection_accel_tpu_layer_2_Pipeline_VITIS_LOOP_234_13}
  {SRCNAME tpu_layer_2_Pipeline_VITIS_LOOP_238_14 MODELNAME tpu_layer_2_Pipeline_VITIS_LOOP_238_14 RTLNAME task_detection_accel_tpu_layer_2_Pipeline_VITIS_LOOP_238_14}
  {SRCNAME tpu_layer_2_Pipeline_VITIS_LOOP_242_15 MODELNAME tpu_layer_2_Pipeline_VITIS_LOOP_242_15 RTLNAME task_detection_accel_tpu_layer_2_Pipeline_VITIS_LOOP_242_15}
  {SRCNAME tpu_layer_2_Pipeline_VITIS_LOOP_246_16 MODELNAME tpu_layer_2_Pipeline_VITIS_LOOP_246_16 RTLNAME task_detection_accel_tpu_layer_2_Pipeline_VITIS_LOOP_246_16}
  {SRCNAME tpu_layer_2_Pipeline_VITIS_LOOP_250_17 MODELNAME tpu_layer_2_Pipeline_VITIS_LOOP_250_17 RTLNAME task_detection_accel_tpu_layer_2_Pipeline_VITIS_LOOP_250_17}
  {SRCNAME tpu_layer_2_Pipeline_VITIS_LOOP_254_18 MODELNAME tpu_layer_2_Pipeline_VITIS_LOOP_254_18 RTLNAME task_detection_accel_tpu_layer_2_Pipeline_VITIS_LOOP_254_18}
  {SRCNAME tpu_layer_2 MODELNAME tpu_layer_2 RTLNAME task_detection_accel_tpu_layer_2
    SUBMODULES {
      {MODELNAME task_detection_accel_tpu_layer_2_tpu_layer_2_stream_ap_fixed_0_stream_ap_fixed_16_6_5_3_0_0_bias_7izb RTLNAME task_detection_accel_tpu_layer_2_tpu_layer_2_stream_ap_fixed_0_stream_ap_fixed_16_6_5_3_0_0_bias_7izb BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME task_detection_accel_tpu_layer_2_p_ZZ11tpu_layer_2RN3hls6streamI8ap_fixedILi16ELi6EL9ap_q_mode5EL9iHb RTLNAME task_detection_accel_tpu_layer_2_p_ZZ11tpu_layer_2RN3hls6streamI8ap_fixedILi16ELi6EL9ap_q_mode5EL9iHb BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME task_detection_accel_tpu_layer_2_local_in_RAM_AUTO_1R1W RTLNAME task_detection_accel_tpu_layer_2_local_in_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME tpu_layer_3_Pipeline_VITIS_LOOP_268_1 MODELNAME tpu_layer_3_Pipeline_VITIS_LOOP_268_1 RTLNAME task_detection_accel_tpu_layer_3_Pipeline_VITIS_LOOP_268_1}
  {SRCNAME tpu_layer_3_Pipeline_VITIS_LOOP_283_2 MODELNAME tpu_layer_3_Pipeline_VITIS_LOOP_283_2 RTLNAME task_detection_accel_tpu_layer_3_Pipeline_VITIS_LOOP_283_2}
  {SRCNAME tpu_layer_3_Pipeline_VITIS_LOOP_284_3_VITIS_LOOP_285_4_VITIS_LOOP_286_5_VITIS_LO MODELNAME tpu_layer_3_Pipeline_VITIS_LOOP_284_3_VITIS_LOOP_285_4_VITIS_LOOP_286_5_VITIS_LO RTLNAME task_detection_accel_tpu_layer_3_Pipeline_VITIS_LOOP_284_3_VITIS_LOOP_285_4_VITIS_LOOP_286_5_VITIS_LO}
  {SRCNAME tpu_layer_3_Pipeline_VITIS_LOOP_329_11 MODELNAME tpu_layer_3_Pipeline_VITIS_LOOP_329_11 RTLNAME task_detection_accel_tpu_layer_3_Pipeline_VITIS_LOOP_329_11}
  {SRCNAME tpu_layer_3_Pipeline_VITIS_LOOP_333_12 MODELNAME tpu_layer_3_Pipeline_VITIS_LOOP_333_12 RTLNAME task_detection_accel_tpu_layer_3_Pipeline_VITIS_LOOP_333_12}
  {SRCNAME tpu_layer_3_Pipeline_VITIS_LOOP_337_13 MODELNAME tpu_layer_3_Pipeline_VITIS_LOOP_337_13 RTLNAME task_detection_accel_tpu_layer_3_Pipeline_VITIS_LOOP_337_13}
  {SRCNAME tpu_layer_3_Pipeline_VITIS_LOOP_341_14 MODELNAME tpu_layer_3_Pipeline_VITIS_LOOP_341_14 RTLNAME task_detection_accel_tpu_layer_3_Pipeline_VITIS_LOOP_341_14}
  {SRCNAME tpu_layer_3_Pipeline_VITIS_LOOP_345_15 MODELNAME tpu_layer_3_Pipeline_VITIS_LOOP_345_15 RTLNAME task_detection_accel_tpu_layer_3_Pipeline_VITIS_LOOP_345_15}
  {SRCNAME tpu_layer_3_Pipeline_VITIS_LOOP_349_16 MODELNAME tpu_layer_3_Pipeline_VITIS_LOOP_349_16 RTLNAME task_detection_accel_tpu_layer_3_Pipeline_VITIS_LOOP_349_16}
  {SRCNAME tpu_layer_3_Pipeline_VITIS_LOOP_353_17 MODELNAME tpu_layer_3_Pipeline_VITIS_LOOP_353_17 RTLNAME task_detection_accel_tpu_layer_3_Pipeline_VITIS_LOOP_353_17}
  {SRCNAME tpu_layer_3_Pipeline_VITIS_LOOP_357_18 MODELNAME tpu_layer_3_Pipeline_VITIS_LOOP_357_18 RTLNAME task_detection_accel_tpu_layer_3_Pipeline_VITIS_LOOP_357_18}
  {SRCNAME tpu_layer_3 MODELNAME tpu_layer_3 RTLNAME task_detection_accel_tpu_layer_3
    SUBMODULES {
      {MODELNAME task_detection_accel_tpu_layer_3_tpu_layer_3_stream_ap_fixed_0_stream_ap_fixed_16_6_5_3_0_0_bias_7qXc RTLNAME task_detection_accel_tpu_layer_3_tpu_layer_3_stream_ap_fixed_0_stream_ap_fixed_16_6_5_3_0_0_bias_7qXc BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME task_detection_accel_tpu_layer_3_p_ZZ11tpu_layer_3RN3hls6streamI8ap_fixedILi16ELi6EL9ap_q_mode5EL9q5c RTLNAME task_detection_accel_tpu_layer_3_p_ZZ11tpu_layer_3RN3hls6streamI8ap_fixedILi16ELi6EL9ap_q_mode5EL9q5c BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME task_detection_accel_tpu_layer_3_local_in_RAM_AUTO_1R1W RTLNAME task_detection_accel_tpu_layer_3_local_in_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME scalar_layer_4_Pipeline_VITIS_LOOP_372_1 MODELNAME scalar_layer_4_Pipeline_VITIS_LOOP_372_1 RTLNAME task_detection_accel_scalar_layer_4_Pipeline_VITIS_LOOP_372_1}
  {SRCNAME scalar_layer_4_Pipeline_VITIS_LOOP_377_2 MODELNAME scalar_layer_4_Pipeline_VITIS_LOOP_377_2 RTLNAME task_detection_accel_scalar_layer_4_Pipeline_VITIS_LOOP_377_2}
  {SRCNAME scalar_layer_4 MODELNAME scalar_layer_4 RTLNAME task_detection_accel_scalar_layer_4}
  {SRCNAME Block_for.end_proc MODELNAME Block_for_end_proc RTLNAME task_detection_accel_Block_for_end_proc
    SUBMODULES {
      {MODELNAME task_detection_accel_ctlz_16_16_1_1 RTLNAME task_detection_accel_ctlz_16_16_1_1 BINDTYPE op TYPE ctlz IMPL auto}
    }
  }
  {SRCNAME Block_entry_proc MODELNAME Block_entry_proc RTLNAME task_detection_accel_Block_entry_proc}
  {SRCNAME task_detection_accel MODELNAME task_detection_accel RTLNAME task_detection_accel IS_TOP 1
    SUBMODULES {
      {MODELNAME task_detection_accel_fifo_w64_d8_S RTLNAME task_detection_accel_fifo_w64_d8_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME output_r_c_U}
      {MODELNAME task_detection_accel_fifo_w16_d2_S RTLNAME task_detection_accel_fifo_w16_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME stream_in_U}
      {MODELNAME task_detection_accel_fifo_w16_d2_S RTLNAME task_detection_accel_fifo_w16_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME stream_l1_to_l2_U}
      {MODELNAME task_detection_accel_fifo_w16_d2_S RTLNAME task_detection_accel_fifo_w16_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME stream_l2_to_l3_U}
      {MODELNAME task_detection_accel_fifo_w16_d2_S RTLNAME task_detection_accel_fifo_w16_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME stream_l3_to_l4_U}
      {MODELNAME task_detection_accel_fifo_w16_d2_S RTLNAME task_detection_accel_fifo_w16_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME l4_out_U}
      {MODELNAME task_detection_accel_fifo_w32_d2_S RTLNAME task_detection_accel_fifo_w32_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME p_loc_channel_U}
      {MODELNAME task_detection_accel_start_for_tpu_layer_1_U0 RTLNAME task_detection_accel_start_for_tpu_layer_1_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_tpu_layer_1_U0_U}
      {MODELNAME task_detection_accel_start_for_tpu_layer_2_U0 RTLNAME task_detection_accel_start_for_tpu_layer_2_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_tpu_layer_2_U0_U}
      {MODELNAME task_detection_accel_start_for_tpu_layer_3_U0 RTLNAME task_detection_accel_start_for_tpu_layer_3_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_tpu_layer_3_U0_U}
      {MODELNAME task_detection_accel_start_for_scalar_layer_4_U0 RTLNAME task_detection_accel_start_for_scalar_layer_4_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_scalar_layer_4_U0_U}
      {MODELNAME task_detection_accel_gmem0_m_axi RTLNAME task_detection_accel_gmem0_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME task_detection_accel_gmem1_m_axi RTLNAME task_detection_accel_gmem1_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME task_detection_accel_control_s_axi RTLNAME task_detection_accel_control_s_axi BINDTYPE interface TYPE interface_s_axilite}
      {MODELNAME task_detection_accel_control_r_s_axi RTLNAME task_detection_accel_control_r_s_axi BINDTYPE interface TYPE interface_s_axilite}
    }
  }
}
