-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity yolo_backbone_block_leaky_relu_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    stream_l1_out_dout : IN STD_LOGIC_VECTOR (255 downto 0);
    stream_l1_out_empty_n : IN STD_LOGIC;
    stream_l1_out_read : OUT STD_LOGIC;
    stream_l1_out_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    stream_l1_out_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    stream_relu_out_din : OUT STD_LOGIC_VECTOR (255 downto 0);
    stream_relu_out_full_n : IN STD_LOGIC;
    stream_relu_out_write : OUT STD_LOGIC;
    stream_relu_out_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    stream_relu_out_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC );
end;


architecture behav of yolo_backbone_block_leaky_relu_1 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_C4 : STD_LOGIC_VECTOR (7 downto 0) := "11000100";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_8F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001111";
    constant ap_const_lv32_90 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010000";
    constant ap_const_lv32_9F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011111";
    constant ap_const_lv32_A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100000";
    constant ap_const_lv32_AF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101111";
    constant ap_const_lv32_B0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110000";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv32_C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000000";
    constant ap_const_lv32_CF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001111";
    constant ap_const_lv32_D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010000";
    constant ap_const_lv32_DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011111";
    constant ap_const_lv32_E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100000";
    constant ap_const_lv32_EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101111";
    constant ap_const_lv32_F0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110000";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv24_66 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000001100110";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal internal_ap_ready : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln84_fu_135_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal stream_l1_out_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal stream_relu_out_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal p_in_fu_152_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_in_reg_914 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal p_in_1_fu_156_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_in_1_reg_920 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_in_2_fu_166_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_in_2_reg_926 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_in_3_fu_176_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_in_3_reg_932 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_in_4_fu_186_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_in_4_reg_938 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_in_5_fu_196_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_in_5_reg_944 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_in_6_fu_206_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_in_6_reg_950 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_in_7_fu_216_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_in_7_reg_956 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_in_8_fu_226_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_in_8_reg_962 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_in_9_fu_236_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_in_9_reg_968 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_in_15_fu_246_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_in_15_reg_974 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_in_10_fu_256_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_in_10_reg_980 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_in_11_fu_266_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_in_11_reg_986 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_in_12_fu_276_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_in_12_reg_992 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_in_13_fu_286_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_in_13_reg_998 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_in_14_fu_296_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_in_14_reg_1004 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln90_fu_306_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_reg_1010 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_1_fu_312_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_1_reg_1015 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_2_fu_318_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_2_reg_1020 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_3_fu_324_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_3_reg_1025 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_4_fu_330_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_4_reg_1030 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_5_fu_336_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_5_reg_1035 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_6_fu_342_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_6_reg_1040 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_7_fu_348_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_7_reg_1045 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_8_fu_354_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_8_reg_1050 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_9_fu_360_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_9_reg_1055 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_10_fu_366_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_10_reg_1060 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_11_fu_372_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_11_reg_1065 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_12_fu_378_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_12_reg_1070 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_13_fu_384_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_13_reg_1075 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_14_fu_390_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_14_reg_1080 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_15_fu_396_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_15_reg_1085 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_fu_110 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal i_4_fu_141_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal mul_ln93_fu_405_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln93_fu_405_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln_fu_411_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln93_1_fu_421_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln93_1_fu_434_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln93_1_fu_434_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln93_1_fu_440_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln93_3_fu_450_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln93_2_fu_463_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln93_2_fu_463_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln93_2_fu_469_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln93_5_fu_479_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln93_3_fu_492_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln93_3_fu_492_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln93_3_fu_498_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln93_7_fu_508_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln93_4_fu_521_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln93_4_fu_521_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln93_4_fu_527_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln93_9_fu_537_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln93_5_fu_550_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln93_5_fu_550_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln93_5_fu_556_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln93_11_fu_566_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln93_6_fu_579_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln93_6_fu_579_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln93_6_fu_585_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln93_13_fu_595_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln93_7_fu_608_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln93_7_fu_608_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln93_7_fu_614_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln93_15_fu_624_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln93_8_fu_637_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln93_8_fu_637_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln93_8_fu_643_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln93_17_fu_653_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln93_9_fu_666_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln93_9_fu_666_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln93_9_fu_672_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln93_19_fu_682_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln93_10_fu_695_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln93_10_fu_695_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln93_s_fu_701_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln93_21_fu_711_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln93_11_fu_724_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln93_11_fu_724_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln93_10_fu_730_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln93_23_fu_740_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln93_12_fu_753_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln93_12_fu_753_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln93_11_fu_759_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln93_25_fu_769_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln93_13_fu_782_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln93_13_fu_782_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln93_12_fu_788_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln93_27_fu_798_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln93_14_fu_811_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln93_14_fu_811_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln93_13_fu_817_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln93_29_fu_827_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln93_15_fu_840_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln93_15_fu_840_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln93_14_fu_846_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln93_31_fu_856_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_out_15_fu_860_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_out_14_fu_831_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_out_13_fu_802_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_out_12_fu_773_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_out_11_fu_744_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_out_10_fu_715_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_out_9_fu_686_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_out_8_fu_657_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_out_7_fu_628_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_out_6_fu_599_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_out_5_fu_570_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_out_4_fu_541_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_out_3_fu_512_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_out_2_fu_483_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_out_1_fu_454_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_out_fu_425_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_177 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component yolo_backbone_block_mul_16s_8ns_24_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component yolo_backbone_block_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    mul_16s_8ns_24_1_1_U2464 : component yolo_backbone_block_mul_16s_8ns_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 8,
        dout_WIDTH => 24)
    port map (
        din0 => p_in_reg_914,
        din1 => mul_ln93_fu_405_p1,
        dout => mul_ln93_fu_405_p2);

    mul_16s_8ns_24_1_1_U2465 : component yolo_backbone_block_mul_16s_8ns_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 8,
        dout_WIDTH => 24)
    port map (
        din0 => p_in_1_reg_920,
        din1 => mul_ln93_1_fu_434_p1,
        dout => mul_ln93_1_fu_434_p2);

    mul_16s_8ns_24_1_1_U2466 : component yolo_backbone_block_mul_16s_8ns_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 8,
        dout_WIDTH => 24)
    port map (
        din0 => p_in_2_reg_926,
        din1 => mul_ln93_2_fu_463_p1,
        dout => mul_ln93_2_fu_463_p2);

    mul_16s_8ns_24_1_1_U2467 : component yolo_backbone_block_mul_16s_8ns_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 8,
        dout_WIDTH => 24)
    port map (
        din0 => p_in_3_reg_932,
        din1 => mul_ln93_3_fu_492_p1,
        dout => mul_ln93_3_fu_492_p2);

    mul_16s_8ns_24_1_1_U2468 : component yolo_backbone_block_mul_16s_8ns_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 8,
        dout_WIDTH => 24)
    port map (
        din0 => p_in_4_reg_938,
        din1 => mul_ln93_4_fu_521_p1,
        dout => mul_ln93_4_fu_521_p2);

    mul_16s_8ns_24_1_1_U2469 : component yolo_backbone_block_mul_16s_8ns_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 8,
        dout_WIDTH => 24)
    port map (
        din0 => p_in_5_reg_944,
        din1 => mul_ln93_5_fu_550_p1,
        dout => mul_ln93_5_fu_550_p2);

    mul_16s_8ns_24_1_1_U2470 : component yolo_backbone_block_mul_16s_8ns_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 8,
        dout_WIDTH => 24)
    port map (
        din0 => p_in_6_reg_950,
        din1 => mul_ln93_6_fu_579_p1,
        dout => mul_ln93_6_fu_579_p2);

    mul_16s_8ns_24_1_1_U2471 : component yolo_backbone_block_mul_16s_8ns_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 8,
        dout_WIDTH => 24)
    port map (
        din0 => p_in_7_reg_956,
        din1 => mul_ln93_7_fu_608_p1,
        dout => mul_ln93_7_fu_608_p2);

    mul_16s_8ns_24_1_1_U2472 : component yolo_backbone_block_mul_16s_8ns_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 8,
        dout_WIDTH => 24)
    port map (
        din0 => p_in_8_reg_962,
        din1 => mul_ln93_8_fu_637_p1,
        dout => mul_ln93_8_fu_637_p2);

    mul_16s_8ns_24_1_1_U2473 : component yolo_backbone_block_mul_16s_8ns_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 8,
        dout_WIDTH => 24)
    port map (
        din0 => p_in_9_reg_968,
        din1 => mul_ln93_9_fu_666_p1,
        dout => mul_ln93_9_fu_666_p2);

    mul_16s_8ns_24_1_1_U2474 : component yolo_backbone_block_mul_16s_8ns_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 8,
        dout_WIDTH => 24)
    port map (
        din0 => p_in_15_reg_974,
        din1 => mul_ln93_10_fu_695_p1,
        dout => mul_ln93_10_fu_695_p2);

    mul_16s_8ns_24_1_1_U2475 : component yolo_backbone_block_mul_16s_8ns_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 8,
        dout_WIDTH => 24)
    port map (
        din0 => p_in_10_reg_980,
        din1 => mul_ln93_11_fu_724_p1,
        dout => mul_ln93_11_fu_724_p2);

    mul_16s_8ns_24_1_1_U2476 : component yolo_backbone_block_mul_16s_8ns_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 8,
        dout_WIDTH => 24)
    port map (
        din0 => p_in_11_reg_986,
        din1 => mul_ln93_12_fu_753_p1,
        dout => mul_ln93_12_fu_753_p2);

    mul_16s_8ns_24_1_1_U2477 : component yolo_backbone_block_mul_16s_8ns_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 8,
        dout_WIDTH => 24)
    port map (
        din0 => p_in_12_reg_992,
        din1 => mul_ln93_13_fu_782_p1,
        dout => mul_ln93_13_fu_782_p2);

    mul_16s_8ns_24_1_1_U2478 : component yolo_backbone_block_mul_16s_8ns_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 8,
        dout_WIDTH => 24)
    port map (
        din0 => p_in_13_reg_998,
        din1 => mul_ln93_14_fu_811_p1,
        dout => mul_ln93_14_fu_811_p2);

    mul_16s_8ns_24_1_1_U2479 : component yolo_backbone_block_mul_16s_8ns_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 8,
        dout_WIDTH => 24)
    port map (
        din0 => p_in_14_reg_1004,
        din1 => mul_ln93_15_fu_840_p1,
        dout => mul_ln93_15_fu_840_p2);

    flow_control_loop_pipe_U : component yolo_backbone_block_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => real_start,
        ap_ready => internal_ap_ready,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_177)) then
                if ((icmp_ln84_fu_135_p2 = ap_const_lv1_0)) then 
                    i_fu_110 <= i_4_fu_141_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_110 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln90_10_reg_1060 <= icmp_ln90_10_fu_366_p2;
                icmp_ln90_11_reg_1065 <= icmp_ln90_11_fu_372_p2;
                icmp_ln90_12_reg_1070 <= icmp_ln90_12_fu_378_p2;
                icmp_ln90_13_reg_1075 <= icmp_ln90_13_fu_384_p2;
                icmp_ln90_14_reg_1080 <= icmp_ln90_14_fu_390_p2;
                icmp_ln90_15_reg_1085 <= icmp_ln90_15_fu_396_p2;
                icmp_ln90_1_reg_1015 <= icmp_ln90_1_fu_312_p2;
                icmp_ln90_2_reg_1020 <= icmp_ln90_2_fu_318_p2;
                icmp_ln90_3_reg_1025 <= icmp_ln90_3_fu_324_p2;
                icmp_ln90_4_reg_1030 <= icmp_ln90_4_fu_330_p2;
                icmp_ln90_5_reg_1035 <= icmp_ln90_5_fu_336_p2;
                icmp_ln90_6_reg_1040 <= icmp_ln90_6_fu_342_p2;
                icmp_ln90_7_reg_1045 <= icmp_ln90_7_fu_348_p2;
                icmp_ln90_8_reg_1050 <= icmp_ln90_8_fu_354_p2;
                icmp_ln90_9_reg_1055 <= icmp_ln90_9_fu_360_p2;
                icmp_ln90_reg_1010 <= icmp_ln90_fu_306_p2;
                p_in_10_reg_980 <= stream_l1_out_dout(191 downto 176);
                p_in_11_reg_986 <= stream_l1_out_dout(207 downto 192);
                p_in_12_reg_992 <= stream_l1_out_dout(223 downto 208);
                p_in_13_reg_998 <= stream_l1_out_dout(239 downto 224);
                p_in_14_reg_1004 <= stream_l1_out_dout(255 downto 240);
                p_in_15_reg_974 <= stream_l1_out_dout(175 downto 160);
                p_in_1_reg_920 <= stream_l1_out_dout(31 downto 16);
                p_in_2_reg_926 <= stream_l1_out_dout(47 downto 32);
                p_in_3_reg_932 <= stream_l1_out_dout(63 downto 48);
                p_in_4_reg_938 <= stream_l1_out_dout(79 downto 64);
                p_in_5_reg_944 <= stream_l1_out_dout(95 downto 80);
                p_in_6_reg_950 <= stream_l1_out_dout(111 downto 96);
                p_in_7_reg_956 <= stream_l1_out_dout(127 downto 112);
                p_in_8_reg_962 <= stream_l1_out_dout(143 downto 128);
                p_in_9_reg_968 <= stream_l1_out_dout(159 downto 144);
                p_in_reg_914 <= p_in_fu_152_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, stream_l1_out_empty_n, stream_relu_out_full_n, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_start_int)
    begin
                ap_block_pp0_stage0_01001_grp1 <= ((ap_done_reg = ap_const_logic_1) or ((stream_relu_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((stream_l1_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, stream_l1_out_empty_n, stream_relu_out_full_n, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((stream_relu_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((stream_l1_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, stream_l1_out_empty_n, stream_relu_out_full_n, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_start_int)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_done_reg = ap_const_logic_1) or ((stream_relu_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((stream_l1_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, stream_l1_out_empty_n, stream_relu_out_full_n, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((stream_relu_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((stream_l1_out_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_done_reg = ap_const_logic_1);
    end process;


    ap_condition_177_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
                ap_condition_177 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, icmp_ln84_fu_135_p2, ap_start_int)
    begin
        if (((icmp_ln84_fu_135_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_done_reg, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= internal_ap_ready;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_3_assign_proc : process(ap_CS_fsm_pp0_stage0, i_fu_110, ap_loop_init, ap_block_pp0_stage0, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_3 <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_i_3 <= i_fu_110;
        end if; 
    end process;

    i_4_fu_141_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_3) + unsigned(ap_const_lv8_1));
    icmp_ln84_fu_135_p2 <= "1" when (ap_sig_allocacmp_i_3 = ap_const_lv8_C4) else "0";
    icmp_ln90_10_fu_366_p2 <= "1" when (signed(p_in_15_fu_246_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln90_11_fu_372_p2 <= "1" when (signed(p_in_10_fu_256_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln90_12_fu_378_p2 <= "1" when (signed(p_in_11_fu_266_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln90_13_fu_384_p2 <= "1" when (signed(p_in_12_fu_276_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln90_14_fu_390_p2 <= "1" when (signed(p_in_13_fu_286_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln90_15_fu_396_p2 <= "1" when (signed(p_in_14_fu_296_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln90_1_fu_312_p2 <= "1" when (signed(p_in_1_fu_156_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln90_2_fu_318_p2 <= "1" when (signed(p_in_2_fu_166_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln90_3_fu_324_p2 <= "1" when (signed(p_in_3_fu_176_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln90_4_fu_330_p2 <= "1" when (signed(p_in_4_fu_186_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln90_5_fu_336_p2 <= "1" when (signed(p_in_5_fu_196_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln90_6_fu_342_p2 <= "1" when (signed(p_in_6_fu_206_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln90_7_fu_348_p2 <= "1" when (signed(p_in_7_fu_216_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln90_8_fu_354_p2 <= "1" when (signed(p_in_8_fu_226_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln90_9_fu_360_p2 <= "1" when (signed(p_in_9_fu_236_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln90_fu_306_p2 <= "1" when (signed(p_in_fu_152_p1) > signed(ap_const_lv16_0)) else "0";
    mul_ln93_10_fu_695_p1 <= ap_const_lv24_66(8 - 1 downto 0);
    mul_ln93_11_fu_724_p1 <= ap_const_lv24_66(8 - 1 downto 0);
    mul_ln93_12_fu_753_p1 <= ap_const_lv24_66(8 - 1 downto 0);
    mul_ln93_13_fu_782_p1 <= ap_const_lv24_66(8 - 1 downto 0);
    mul_ln93_14_fu_811_p1 <= ap_const_lv24_66(8 - 1 downto 0);
    mul_ln93_15_fu_840_p1 <= ap_const_lv24_66(8 - 1 downto 0);
    mul_ln93_1_fu_434_p1 <= ap_const_lv24_66(8 - 1 downto 0);
    mul_ln93_2_fu_463_p1 <= ap_const_lv24_66(8 - 1 downto 0);
    mul_ln93_3_fu_492_p1 <= ap_const_lv24_66(8 - 1 downto 0);
    mul_ln93_4_fu_521_p1 <= ap_const_lv24_66(8 - 1 downto 0);
    mul_ln93_5_fu_550_p1 <= ap_const_lv24_66(8 - 1 downto 0);
    mul_ln93_6_fu_579_p1 <= ap_const_lv24_66(8 - 1 downto 0);
    mul_ln93_7_fu_608_p1 <= ap_const_lv24_66(8 - 1 downto 0);
    mul_ln93_8_fu_637_p1 <= ap_const_lv24_66(8 - 1 downto 0);
    mul_ln93_9_fu_666_p1 <= ap_const_lv24_66(8 - 1 downto 0);
    mul_ln93_fu_405_p1 <= ap_const_lv24_66(8 - 1 downto 0);
    p_in_10_fu_256_p4 <= stream_l1_out_dout(191 downto 176);
    p_in_11_fu_266_p4 <= stream_l1_out_dout(207 downto 192);
    p_in_12_fu_276_p4 <= stream_l1_out_dout(223 downto 208);
    p_in_13_fu_286_p4 <= stream_l1_out_dout(239 downto 224);
    p_in_14_fu_296_p4 <= stream_l1_out_dout(255 downto 240);
    p_in_15_fu_246_p4 <= stream_l1_out_dout(175 downto 160);
    p_in_1_fu_156_p4 <= stream_l1_out_dout(31 downto 16);
    p_in_2_fu_166_p4 <= stream_l1_out_dout(47 downto 32);
    p_in_3_fu_176_p4 <= stream_l1_out_dout(63 downto 48);
    p_in_4_fu_186_p4 <= stream_l1_out_dout(79 downto 64);
    p_in_5_fu_196_p4 <= stream_l1_out_dout(95 downto 80);
    p_in_6_fu_206_p4 <= stream_l1_out_dout(111 downto 96);
    p_in_7_fu_216_p4 <= stream_l1_out_dout(127 downto 112);
    p_in_8_fu_226_p4 <= stream_l1_out_dout(143 downto 128);
    p_in_9_fu_236_p4 <= stream_l1_out_dout(159 downto 144);
    p_in_fu_152_p1 <= stream_l1_out_dout(16 - 1 downto 0);
    p_out_10_fu_715_p3 <= 
        p_in_15_reg_974 when (icmp_ln90_10_reg_1060(0) = '1') else 
        sext_ln93_21_fu_711_p1;
    p_out_11_fu_744_p3 <= 
        p_in_10_reg_980 when (icmp_ln90_11_reg_1065(0) = '1') else 
        sext_ln93_23_fu_740_p1;
    p_out_12_fu_773_p3 <= 
        p_in_11_reg_986 when (icmp_ln90_12_reg_1070(0) = '1') else 
        sext_ln93_25_fu_769_p1;
    p_out_13_fu_802_p3 <= 
        p_in_12_reg_992 when (icmp_ln90_13_reg_1075(0) = '1') else 
        sext_ln93_27_fu_798_p1;
    p_out_14_fu_831_p3 <= 
        p_in_13_reg_998 when (icmp_ln90_14_reg_1080(0) = '1') else 
        sext_ln93_29_fu_827_p1;
    p_out_15_fu_860_p3 <= 
        p_in_14_reg_1004 when (icmp_ln90_15_reg_1085(0) = '1') else 
        sext_ln93_31_fu_856_p1;
    p_out_1_fu_454_p3 <= 
        p_in_1_reg_920 when (icmp_ln90_1_reg_1015(0) = '1') else 
        sext_ln93_3_fu_450_p1;
    p_out_2_fu_483_p3 <= 
        p_in_2_reg_926 when (icmp_ln90_2_reg_1020(0) = '1') else 
        sext_ln93_5_fu_479_p1;
    p_out_3_fu_512_p3 <= 
        p_in_3_reg_932 when (icmp_ln90_3_reg_1025(0) = '1') else 
        sext_ln93_7_fu_508_p1;
    p_out_4_fu_541_p3 <= 
        p_in_4_reg_938 when (icmp_ln90_4_reg_1030(0) = '1') else 
        sext_ln93_9_fu_537_p1;
    p_out_5_fu_570_p3 <= 
        p_in_5_reg_944 when (icmp_ln90_5_reg_1035(0) = '1') else 
        sext_ln93_11_fu_566_p1;
    p_out_6_fu_599_p3 <= 
        p_in_6_reg_950 when (icmp_ln90_6_reg_1040(0) = '1') else 
        sext_ln93_13_fu_595_p1;
    p_out_7_fu_628_p3 <= 
        p_in_7_reg_956 when (icmp_ln90_7_reg_1045(0) = '1') else 
        sext_ln93_15_fu_624_p1;
    p_out_8_fu_657_p3 <= 
        p_in_8_reg_962 when (icmp_ln90_8_reg_1050(0) = '1') else 
        sext_ln93_17_fu_653_p1;
    p_out_9_fu_686_p3 <= 
        p_in_9_reg_968 when (icmp_ln90_9_reg_1055(0) = '1') else 
        sext_ln93_19_fu_682_p1;
    p_out_fu_425_p3 <= 
        p_in_reg_914 when (icmp_ln90_reg_1010(0) = '1') else 
        sext_ln93_1_fu_421_p1;

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

        sext_ln93_11_fu_566_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln93_5_fu_556_p4),16));

        sext_ln93_13_fu_595_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln93_6_fu_585_p4),16));

        sext_ln93_15_fu_624_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln93_7_fu_614_p4),16));

        sext_ln93_17_fu_653_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln93_8_fu_643_p4),16));

        sext_ln93_19_fu_682_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln93_9_fu_672_p4),16));

        sext_ln93_1_fu_421_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_411_p4),16));

        sext_ln93_21_fu_711_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln93_s_fu_701_p4),16));

        sext_ln93_23_fu_740_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln93_10_fu_730_p4),16));

        sext_ln93_25_fu_769_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln93_11_fu_759_p4),16));

        sext_ln93_27_fu_798_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln93_12_fu_788_p4),16));

        sext_ln93_29_fu_827_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln93_13_fu_817_p4),16));

        sext_ln93_31_fu_856_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln93_14_fu_846_p4),16));

        sext_ln93_3_fu_450_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln93_1_fu_440_p4),16));

        sext_ln93_5_fu_479_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln93_2_fu_469_p4),16));

        sext_ln93_7_fu_508_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln93_3_fu_498_p4),16));

        sext_ln93_9_fu_537_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln93_4_fu_527_p4),16));

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;


    stream_l1_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, stream_l1_out_empty_n, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_l1_out_blk_n <= stream_l1_out_empty_n;
        else 
            stream_l1_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    stream_l1_out_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_l1_out_read <= ap_const_logic_1;
        else 
            stream_l1_out_read <= ap_const_logic_0;
        end if; 
    end process;


    stream_relu_out_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, stream_relu_out_full_n, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            stream_relu_out_blk_n <= stream_relu_out_full_n;
        else 
            stream_relu_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    stream_relu_out_din <= (((((((((((((((p_out_15_fu_860_p3 & p_out_14_fu_831_p3) & p_out_13_fu_802_p3) & p_out_12_fu_773_p3) & p_out_11_fu_744_p3) & p_out_10_fu_715_p3) & p_out_9_fu_686_p3) & p_out_8_fu_657_p3) & p_out_7_fu_628_p3) & p_out_6_fu_599_p3) & p_out_5_fu_570_p3) & p_out_4_fu_541_p3) & p_out_3_fu_512_p3) & p_out_2_fu_483_p3) & p_out_1_fu_454_p3) & p_out_fu_425_p3);

    stream_relu_out_write_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            stream_relu_out_write <= ap_const_logic_1;
        else 
            stream_relu_out_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln93_10_fu_730_p4 <= mul_ln93_11_fu_724_p2(23 downto 10);
    trunc_ln93_11_fu_759_p4 <= mul_ln93_12_fu_753_p2(23 downto 10);
    trunc_ln93_12_fu_788_p4 <= mul_ln93_13_fu_782_p2(23 downto 10);
    trunc_ln93_13_fu_817_p4 <= mul_ln93_14_fu_811_p2(23 downto 10);
    trunc_ln93_14_fu_846_p4 <= mul_ln93_15_fu_840_p2(23 downto 10);
    trunc_ln93_1_fu_440_p4 <= mul_ln93_1_fu_434_p2(23 downto 10);
    trunc_ln93_2_fu_469_p4 <= mul_ln93_2_fu_463_p2(23 downto 10);
    trunc_ln93_3_fu_498_p4 <= mul_ln93_3_fu_492_p2(23 downto 10);
    trunc_ln93_4_fu_527_p4 <= mul_ln93_4_fu_521_p2(23 downto 10);
    trunc_ln93_5_fu_556_p4 <= mul_ln93_5_fu_550_p2(23 downto 10);
    trunc_ln93_6_fu_585_p4 <= mul_ln93_6_fu_579_p2(23 downto 10);
    trunc_ln93_7_fu_614_p4 <= mul_ln93_7_fu_608_p2(23 downto 10);
    trunc_ln93_8_fu_643_p4 <= mul_ln93_8_fu_637_p2(23 downto 10);
    trunc_ln93_9_fu_672_p4 <= mul_ln93_9_fu_666_p2(23 downto 10);
    trunc_ln93_s_fu_701_p4 <= mul_ln93_10_fu_695_p2(23 downto 10);
    trunc_ln_fu_411_p4 <= mul_ln93_fu_405_p2(23 downto 10);
end behav;
