-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity yolo_npu_v2_core_yolo_npu_v2_core_Pipeline_VITIS_LOOP_123_17 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    acc_32 : IN STD_LOGIC_VECTOR (15 downto 0);
    acc_31_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    acc_31_out_ap_vld : OUT STD_LOGIC;
    acc_30_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    acc_30_out_ap_vld : OUT STD_LOGIC;
    acc_29_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    acc_29_out_ap_vld : OUT STD_LOGIC;
    acc_28_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    acc_28_out_ap_vld : OUT STD_LOGIC;
    acc_27_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    acc_27_out_ap_vld : OUT STD_LOGIC;
    acc_26_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    acc_26_out_ap_vld : OUT STD_LOGIC;
    acc_25_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    acc_25_out_ap_vld : OUT STD_LOGIC;
    acc_24_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    acc_24_out_ap_vld : OUT STD_LOGIC;
    acc_23_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    acc_23_out_ap_vld : OUT STD_LOGIC;
    acc_22_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    acc_22_out_ap_vld : OUT STD_LOGIC;
    acc_21_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    acc_21_out_ap_vld : OUT STD_LOGIC;
    acc_20_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    acc_20_out_ap_vld : OUT STD_LOGIC;
    acc_19_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    acc_19_out_ap_vld : OUT STD_LOGIC;
    acc_18_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    acc_18_out_ap_vld : OUT STD_LOGIC;
    acc_17_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    acc_17_out_ap_vld : OUT STD_LOGIC;
    acc_16_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    acc_16_out_ap_vld : OUT STD_LOGIC;
    acc_15_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    acc_15_out_ap_vld : OUT STD_LOGIC;
    acc_14_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    acc_14_out_ap_vld : OUT STD_LOGIC;
    acc_13_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    acc_13_out_ap_vld : OUT STD_LOGIC;
    acc_12_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    acc_12_out_ap_vld : OUT STD_LOGIC;
    acc_11_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    acc_11_out_ap_vld : OUT STD_LOGIC;
    acc_10_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    acc_10_out_ap_vld : OUT STD_LOGIC;
    acc_9_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    acc_9_out_ap_vld : OUT STD_LOGIC;
    acc_8_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    acc_8_out_ap_vld : OUT STD_LOGIC;
    acc_7_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    acc_7_out_ap_vld : OUT STD_LOGIC;
    acc_6_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    acc_6_out_ap_vld : OUT STD_LOGIC;
    acc_5_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    acc_5_out_ap_vld : OUT STD_LOGIC;
    acc_4_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    acc_4_out_ap_vld : OUT STD_LOGIC;
    acc_3_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    acc_3_out_ap_vld : OUT STD_LOGIC;
    acc_2_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    acc_2_out_ap_vld : OUT STD_LOGIC;
    acc_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    acc_1_out_ap_vld : OUT STD_LOGIC;
    acc_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    acc_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of yolo_npu_v2_core_yolo_npu_v2_core_Pipeline_VITIS_LOOP_123_17 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_lv5_5 : STD_LOGIC_VECTOR (4 downto 0) := "00101";
    constant ap_const_lv5_6 : STD_LOGIC_VECTOR (4 downto 0) := "00110";
    constant ap_const_lv5_7 : STD_LOGIC_VECTOR (4 downto 0) := "00111";
    constant ap_const_lv5_8 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_const_lv5_9 : STD_LOGIC_VECTOR (4 downto 0) := "01001";
    constant ap_const_lv5_A : STD_LOGIC_VECTOR (4 downto 0) := "01010";
    constant ap_const_lv5_B : STD_LOGIC_VECTOR (4 downto 0) := "01011";
    constant ap_const_lv5_C : STD_LOGIC_VECTOR (4 downto 0) := "01100";
    constant ap_const_lv5_D : STD_LOGIC_VECTOR (4 downto 0) := "01101";
    constant ap_const_lv5_E : STD_LOGIC_VECTOR (4 downto 0) := "01110";
    constant ap_const_lv5_F : STD_LOGIC_VECTOR (4 downto 0) := "01111";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_11 : STD_LOGIC_VECTOR (4 downto 0) := "10001";
    constant ap_const_lv5_12 : STD_LOGIC_VECTOR (4 downto 0) := "10010";
    constant ap_const_lv5_13 : STD_LOGIC_VECTOR (4 downto 0) := "10011";
    constant ap_const_lv5_14 : STD_LOGIC_VECTOR (4 downto 0) := "10100";
    constant ap_const_lv5_15 : STD_LOGIC_VECTOR (4 downto 0) := "10101";
    constant ap_const_lv5_16 : STD_LOGIC_VECTOR (4 downto 0) := "10110";
    constant ap_const_lv5_17 : STD_LOGIC_VECTOR (4 downto 0) := "10111";
    constant ap_const_lv5_18 : STD_LOGIC_VECTOR (4 downto 0) := "11000";
    constant ap_const_lv5_19 : STD_LOGIC_VECTOR (4 downto 0) := "11001";
    constant ap_const_lv5_1A : STD_LOGIC_VECTOR (4 downto 0) := "11010";
    constant ap_const_lv5_1B : STD_LOGIC_VECTOR (4 downto 0) := "11011";
    constant ap_const_lv5_1C : STD_LOGIC_VECTOR (4 downto 0) := "11100";
    constant ap_const_lv5_1D : STD_LOGIC_VECTOR (4 downto 0) := "11101";
    constant ap_const_lv5_1E : STD_LOGIC_VECTOR (4 downto 0) := "11110";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln123_fu_526_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal i_fu_156 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal add_ln123_fu_532_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_fu_160 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal trunc_ln123_fu_538_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal acc_1_fu_164 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal acc_2_fu_168 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal acc_3_fu_172 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal acc_4_fu_176 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal acc_5_fu_180 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal acc_6_fu_184 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal acc_7_fu_188 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal acc_8_fu_192 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal acc_9_fu_196 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal acc_10_fu_200 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal acc_11_fu_204 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal acc_12_fu_208 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal acc_13_fu_212 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal acc_14_fu_216 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal acc_15_fu_220 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal acc_16_fu_224 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal acc_17_fu_228 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal acc_18_fu_232 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal acc_19_fu_236 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal acc_20_fu_240 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal acc_21_fu_244 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal acc_22_fu_248 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal acc_23_fu_252 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal acc_24_fu_256 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal acc_25_fu_260 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal acc_26_fu_264 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal acc_27_fu_268 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal acc_28_fu_272 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal acc_29_fu_276 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal acc_30_fu_280 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal acc_31_fu_284 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component yolo_npu_v2_core_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component yolo_npu_v2_core_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_156_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((icmp_ln123_fu_526_p2 = ap_const_lv1_0)) then 
                    i_fu_156 <= add_ln123_fu_532_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_156 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_fu_526_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln123_fu_538_p1 = ap_const_lv5_A))) then
                acc_10_fu_200 <= acc_32;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_fu_526_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln123_fu_538_p1 = ap_const_lv5_B))) then
                acc_11_fu_204 <= acc_32;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_fu_526_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln123_fu_538_p1 = ap_const_lv5_C))) then
                acc_12_fu_208 <= acc_32;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_fu_526_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln123_fu_538_p1 = ap_const_lv5_D))) then
                acc_13_fu_212 <= acc_32;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_fu_526_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln123_fu_538_p1 = ap_const_lv5_E))) then
                acc_14_fu_216 <= acc_32;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_fu_526_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln123_fu_538_p1 = ap_const_lv5_F))) then
                acc_15_fu_220 <= acc_32;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_fu_526_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln123_fu_538_p1 = ap_const_lv5_10))) then
                acc_16_fu_224 <= acc_32;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_fu_526_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln123_fu_538_p1 = ap_const_lv5_11))) then
                acc_17_fu_228 <= acc_32;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_fu_526_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln123_fu_538_p1 = ap_const_lv5_12))) then
                acc_18_fu_232 <= acc_32;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_fu_526_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln123_fu_538_p1 = ap_const_lv5_13))) then
                acc_19_fu_236 <= acc_32;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_fu_526_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln123_fu_538_p1 = ap_const_lv5_1))) then
                acc_1_fu_164 <= acc_32;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_fu_526_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln123_fu_538_p1 = ap_const_lv5_14))) then
                acc_20_fu_240 <= acc_32;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_fu_526_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln123_fu_538_p1 = ap_const_lv5_15))) then
                acc_21_fu_244 <= acc_32;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_fu_526_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln123_fu_538_p1 = ap_const_lv5_16))) then
                acc_22_fu_248 <= acc_32;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_fu_526_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln123_fu_538_p1 = ap_const_lv5_17))) then
                acc_23_fu_252 <= acc_32;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_fu_526_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln123_fu_538_p1 = ap_const_lv5_18))) then
                acc_24_fu_256 <= acc_32;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_fu_526_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln123_fu_538_p1 = ap_const_lv5_19))) then
                acc_25_fu_260 <= acc_32;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_fu_526_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln123_fu_538_p1 = ap_const_lv5_1A))) then
                acc_26_fu_264 <= acc_32;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_fu_526_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln123_fu_538_p1 = ap_const_lv5_1B))) then
                acc_27_fu_268 <= acc_32;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_fu_526_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln123_fu_538_p1 = ap_const_lv5_1C))) then
                acc_28_fu_272 <= acc_32;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_fu_526_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln123_fu_538_p1 = ap_const_lv5_1D))) then
                acc_29_fu_276 <= acc_32;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_fu_526_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln123_fu_538_p1 = ap_const_lv5_2))) then
                acc_2_fu_168 <= acc_32;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_fu_526_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln123_fu_538_p1 = ap_const_lv5_1E))) then
                acc_30_fu_280 <= acc_32;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_fu_526_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln123_fu_538_p1 = ap_const_lv5_1F))) then
                acc_31_fu_284 <= acc_32;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_fu_526_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln123_fu_538_p1 = ap_const_lv5_3))) then
                acc_3_fu_172 <= acc_32;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_fu_526_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln123_fu_538_p1 = ap_const_lv5_4))) then
                acc_4_fu_176 <= acc_32;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_fu_526_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln123_fu_538_p1 = ap_const_lv5_5))) then
                acc_5_fu_180 <= acc_32;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_fu_526_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln123_fu_538_p1 = ap_const_lv5_6))) then
                acc_6_fu_184 <= acc_32;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_fu_526_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln123_fu_538_p1 = ap_const_lv5_7))) then
                acc_7_fu_188 <= acc_32;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_fu_526_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln123_fu_538_p1 = ap_const_lv5_8))) then
                acc_8_fu_192 <= acc_32;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_fu_526_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln123_fu_538_p1 = ap_const_lv5_9))) then
                acc_9_fu_196 <= acc_32;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_fu_526_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln123_fu_538_p1 = ap_const_lv5_0))) then
                acc_fu_160 <= acc_32;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    acc_10_out <= acc_10_fu_200;

    acc_10_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln123_fu_526_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln123_fu_526_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_10_out_ap_vld <= ap_const_logic_1;
        else 
            acc_10_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_11_out <= acc_11_fu_204;

    acc_11_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln123_fu_526_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln123_fu_526_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_11_out_ap_vld <= ap_const_logic_1;
        else 
            acc_11_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_12_out <= acc_12_fu_208;

    acc_12_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln123_fu_526_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln123_fu_526_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_12_out_ap_vld <= ap_const_logic_1;
        else 
            acc_12_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_13_out <= acc_13_fu_212;

    acc_13_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln123_fu_526_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln123_fu_526_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_13_out_ap_vld <= ap_const_logic_1;
        else 
            acc_13_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_14_out <= acc_14_fu_216;

    acc_14_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln123_fu_526_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln123_fu_526_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_14_out_ap_vld <= ap_const_logic_1;
        else 
            acc_14_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_15_out <= acc_15_fu_220;

    acc_15_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln123_fu_526_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln123_fu_526_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_15_out_ap_vld <= ap_const_logic_1;
        else 
            acc_15_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_16_out <= acc_16_fu_224;

    acc_16_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln123_fu_526_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln123_fu_526_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_16_out_ap_vld <= ap_const_logic_1;
        else 
            acc_16_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_17_out <= acc_17_fu_228;

    acc_17_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln123_fu_526_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln123_fu_526_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_17_out_ap_vld <= ap_const_logic_1;
        else 
            acc_17_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_18_out <= acc_18_fu_232;

    acc_18_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln123_fu_526_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln123_fu_526_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_18_out_ap_vld <= ap_const_logic_1;
        else 
            acc_18_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_19_out <= acc_19_fu_236;

    acc_19_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln123_fu_526_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln123_fu_526_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_19_out_ap_vld <= ap_const_logic_1;
        else 
            acc_19_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_1_out <= acc_1_fu_164;

    acc_1_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln123_fu_526_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln123_fu_526_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_1_out_ap_vld <= ap_const_logic_1;
        else 
            acc_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_20_out <= acc_20_fu_240;

    acc_20_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln123_fu_526_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln123_fu_526_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_20_out_ap_vld <= ap_const_logic_1;
        else 
            acc_20_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_21_out <= acc_21_fu_244;

    acc_21_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln123_fu_526_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln123_fu_526_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_21_out_ap_vld <= ap_const_logic_1;
        else 
            acc_21_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_22_out <= acc_22_fu_248;

    acc_22_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln123_fu_526_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln123_fu_526_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_22_out_ap_vld <= ap_const_logic_1;
        else 
            acc_22_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_23_out <= acc_23_fu_252;

    acc_23_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln123_fu_526_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln123_fu_526_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_23_out_ap_vld <= ap_const_logic_1;
        else 
            acc_23_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_24_out <= acc_24_fu_256;

    acc_24_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln123_fu_526_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln123_fu_526_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_24_out_ap_vld <= ap_const_logic_1;
        else 
            acc_24_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_25_out <= acc_25_fu_260;

    acc_25_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln123_fu_526_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln123_fu_526_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_25_out_ap_vld <= ap_const_logic_1;
        else 
            acc_25_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_26_out <= acc_26_fu_264;

    acc_26_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln123_fu_526_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln123_fu_526_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_26_out_ap_vld <= ap_const_logic_1;
        else 
            acc_26_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_27_out <= acc_27_fu_268;

    acc_27_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln123_fu_526_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln123_fu_526_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_27_out_ap_vld <= ap_const_logic_1;
        else 
            acc_27_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_28_out <= acc_28_fu_272;

    acc_28_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln123_fu_526_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln123_fu_526_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_28_out_ap_vld <= ap_const_logic_1;
        else 
            acc_28_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_29_out <= acc_29_fu_276;

    acc_29_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln123_fu_526_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln123_fu_526_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_29_out_ap_vld <= ap_const_logic_1;
        else 
            acc_29_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_2_out <= acc_2_fu_168;

    acc_2_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln123_fu_526_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln123_fu_526_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_2_out_ap_vld <= ap_const_logic_1;
        else 
            acc_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_30_out <= acc_30_fu_280;

    acc_30_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln123_fu_526_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln123_fu_526_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_30_out_ap_vld <= ap_const_logic_1;
        else 
            acc_30_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_31_out <= acc_31_fu_284;

    acc_31_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln123_fu_526_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln123_fu_526_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_31_out_ap_vld <= ap_const_logic_1;
        else 
            acc_31_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_3_out <= acc_3_fu_172;

    acc_3_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln123_fu_526_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln123_fu_526_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_3_out_ap_vld <= ap_const_logic_1;
        else 
            acc_3_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_4_out <= acc_4_fu_176;

    acc_4_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln123_fu_526_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln123_fu_526_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_4_out_ap_vld <= ap_const_logic_1;
        else 
            acc_4_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_5_out <= acc_5_fu_180;

    acc_5_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln123_fu_526_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln123_fu_526_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_5_out_ap_vld <= ap_const_logic_1;
        else 
            acc_5_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_6_out <= acc_6_fu_184;

    acc_6_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln123_fu_526_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln123_fu_526_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_6_out_ap_vld <= ap_const_logic_1;
        else 
            acc_6_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_7_out <= acc_7_fu_188;

    acc_7_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln123_fu_526_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln123_fu_526_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_7_out_ap_vld <= ap_const_logic_1;
        else 
            acc_7_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_8_out <= acc_8_fu_192;

    acc_8_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln123_fu_526_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln123_fu_526_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_8_out_ap_vld <= ap_const_logic_1;
        else 
            acc_8_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_9_out <= acc_9_fu_196;

    acc_9_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln123_fu_526_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln123_fu_526_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_9_out_ap_vld <= ap_const_logic_1;
        else 
            acc_9_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_out <= acc_fu_160;

    acc_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln123_fu_526_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln123_fu_526_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_out_ap_vld <= ap_const_logic_1;
        else 
            acc_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln123_fu_532_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv6_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln123_fu_526_p2)
    begin
        if (((icmp_ln123_fu_526_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_state1, i_fu_156, ap_loop_init)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_156;
        end if; 
    end process;

    icmp_ln123_fu_526_p2 <= "1" when (ap_sig_allocacmp_i_1 = ap_const_lv6_20) else "0";
    trunc_ln123_fu_538_p1 <= ap_sig_allocacmp_i_1(5 - 1 downto 0);
end behav;
