-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity task_detection_accel_task_detection_accel_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_86_3_VITIS_LOOP_87_4_VI is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_ce0 : OUT STD_LOGIC;
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_we0 : OUT STD_LOGIC;
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_8_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_8_ce0 : OUT STD_LOGIC;
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_8_we0 : OUT STD_LOGIC;
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_8_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_9_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_9_ce0 : OUT STD_LOGIC;
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_9_we0 : OUT STD_LOGIC;
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_9_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_10_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_10_ce0 : OUT STD_LOGIC;
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_10_we0 : OUT STD_LOGIC;
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_10_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_11_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_11_ce0 : OUT STD_LOGIC;
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_11_we0 : OUT STD_LOGIC;
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_11_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_12_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_12_ce0 : OUT STD_LOGIC;
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_12_we0 : OUT STD_LOGIC;
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_12_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_13_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_13_ce0 : OUT STD_LOGIC;
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_13_we0 : OUT STD_LOGIC;
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_13_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_14_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_14_ce0 : OUT STD_LOGIC;
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_14_we0 : OUT STD_LOGIC;
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_14_d0 : OUT STD_LOGIC_VECTOR (3 downto 0) );
end;


architecture behav of task_detection_accel_task_detection_accel_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_86_3_VITIS_LOOP_87_4_VI is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv13_800 : STD_LOGIC_VECTOR (12 downto 0) := "0100000000000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv8_40 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln85_fu_274_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln86_fu_289_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln86_reg_626 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln85_1_fu_313_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln85_1_reg_632 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_319_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_reg_637 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln88_mid211_fu_343_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln88_mid211_reg_642 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln88_fu_369_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln88_reg_647 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln89_2_fu_547_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal c_fu_90 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln88_fu_391_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal r_fu_94 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal select_ln87_fu_504_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten_fu_98 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln87_1_fu_403_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal i_fu_102 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal select_ln86_fu_491_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal indvar_flatten12_fu_106 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal select_ln86_1_fu_417_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal o_fu_110 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal select_ln85_1_fu_467_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal indvar_flatten35_fu_114 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal add_ln85_1_fu_280_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_13_we0_local : STD_LOGIC;
    signal tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_13_ce0_local : STD_LOGIC;
    signal tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_12_we0_local : STD_LOGIC;
    signal tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_12_ce0_local : STD_LOGIC;
    signal tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_11_we0_local : STD_LOGIC;
    signal tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_11_ce0_local : STD_LOGIC;
    signal tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_10_we0_local : STD_LOGIC;
    signal tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_10_ce0_local : STD_LOGIC;
    signal tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_9_we0_local : STD_LOGIC;
    signal tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_9_ce0_local : STD_LOGIC;
    signal tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_8_we0_local : STD_LOGIC;
    signal tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_8_ce0_local : STD_LOGIC;
    signal tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_we0_local : STD_LOGIC;
    signal tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_ce0_local : STD_LOGIC;
    signal tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_14_we0_local : STD_LOGIC;
    signal tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_14_ce0_local : STD_LOGIC;
    signal icmp_ln87_fu_307_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln85_fu_295_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_flatten_not_fu_325_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_exitcond_flatten_mid234_fu_331_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln85_fu_337_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln88_fu_301_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_54_fu_349_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_55_fu_355_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal c_mid2_fu_361_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln87_1_fu_397_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln86_1_fu_411_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln85_fu_454_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln85_fu_460_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln86_fu_478_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal r_mid26_fu_484_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln87_fu_498_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln86_fu_474_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_6_fu_511_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln89_fu_519_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln89_fu_523_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_fu_529_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln89_1_fu_537_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln89_1_fu_541_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component task_detection_accel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component task_detection_accel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    c_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    c_fu_90 <= ap_const_lv4_0;
                elsif (((icmp_ln85_fu_274_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    c_fu_90 <= add_ln88_fu_391_p2;
                end if;
            end if; 
        end if;
    end process;

    i_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    i_fu_102 <= ap_const_lv6_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    i_fu_102 <= select_ln86_fu_491_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten12_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten12_fu_106 <= ap_const_lv13_0;
                elsif (((icmp_ln85_fu_274_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten12_fu_106 <= select_ln86_1_fu_417_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten35_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten35_fu_114 <= ap_const_lv16_0;
                elsif (((icmp_ln85_fu_274_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten35_fu_114 <= add_ln85_1_fu_280_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_98 <= ap_const_lv8_0;
                elsif (((icmp_ln85_fu_274_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten_fu_98 <= select_ln87_1_fu_403_p3;
                end if;
            end if; 
        end if;
    end process;

    o_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    o_fu_110 <= ap_const_lv5_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    o_fu_110 <= select_ln85_1_fu_467_p3;
                end if;
            end if; 
        end if;
    end process;

    r_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    r_fu_94 <= ap_const_lv4_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    r_fu_94 <= select_ln87_fu_504_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                and_ln85_1_reg_632 <= and_ln85_1_fu_313_p2;
                empty_reg_637 <= empty_fu_319_p2;
                icmp_ln86_reg_626 <= icmp_ln86_fu_289_p2;
                icmp_ln88_mid211_reg_642 <= icmp_ln88_mid211_fu_343_p2;
                trunc_ln88_reg_647 <= trunc_ln88_fu_369_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln85_1_fu_280_p2 <= std_logic_vector(unsigned(indvar_flatten35_fu_114) + unsigned(ap_const_lv16_1));
    add_ln85_fu_454_p2 <= std_logic_vector(unsigned(o_fu_110) + unsigned(ap_const_lv5_1));
    add_ln86_1_fu_411_p2 <= std_logic_vector(unsigned(indvar_flatten12_fu_106) + unsigned(ap_const_lv13_1));
    add_ln86_fu_478_p2 <= std_logic_vector(unsigned(select_ln85_fu_460_p3) + unsigned(ap_const_lv6_1));
    add_ln87_1_fu_397_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_98) + unsigned(ap_const_lv8_1));
    add_ln87_fu_498_p2 <= std_logic_vector(unsigned(r_mid26_fu_484_p3) + unsigned(ap_const_lv4_1));
    add_ln88_fu_391_p2 <= std_logic_vector(unsigned(c_mid2_fu_361_p3) + unsigned(ap_const_lv4_1));
    add_ln89_1_fu_541_p2 <= std_logic_vector(unsigned(tmp_fu_529_p3) + unsigned(zext_ln89_1_fu_537_p1));
    add_ln89_fu_523_p2 <= std_logic_vector(unsigned(tmp_6_fu_511_p3) + unsigned(zext_ln89_fu_519_p1));
    and_ln85_1_fu_313_p2 <= (xor_ln85_fu_295_p2 and icmp_ln87_fu_307_p2);
    and_ln85_fu_337_p2 <= (xor_ln85_fu_295_p2 and not_exitcond_flatten_mid234_fu_331_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln85_fu_274_p2)
    begin
        if (((icmp_ln85_fu_274_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    c_mid2_fu_361_p3 <= 
        ap_const_lv4_0 when (empty_55_fu_355_p2(0) = '1') else 
        c_fu_90;
    empty_54_fu_349_p2 <= (icmp_ln88_mid211_fu_343_p2 or and_ln85_1_fu_313_p2);
    empty_55_fu_355_p2 <= (icmp_ln86_fu_289_p2 or empty_54_fu_349_p2);
    empty_fu_319_p2 <= (icmp_ln86_fu_289_p2 or and_ln85_1_fu_313_p2);
    exitcond_flatten_not_fu_325_p2 <= (icmp_ln87_fu_307_p2 xor ap_const_lv1_1);
    icmp_ln85_fu_274_p2 <= "1" when (indvar_flatten35_fu_114 = ap_const_lv16_8000) else "0";
    icmp_ln86_fu_289_p2 <= "1" when (indvar_flatten12_fu_106 = ap_const_lv13_800) else "0";
    icmp_ln87_fu_307_p2 <= "1" when (indvar_flatten_fu_98 = ap_const_lv8_40) else "0";
    icmp_ln88_fu_301_p2 <= "1" when (c_fu_90 = ap_const_lv4_8) else "0";
    icmp_ln88_mid211_fu_343_p2 <= (icmp_ln88_fu_301_p2 and and_ln85_fu_337_p2);
    not_exitcond_flatten_mid234_fu_331_p2 <= (icmp_ln86_fu_289_p2 or exitcond_flatten_not_fu_325_p2);
    r_mid26_fu_484_p3 <= 
        ap_const_lv4_0 when (empty_reg_637(0) = '1') else 
        r_fu_94;
    select_ln85_1_fu_467_p3 <= 
        add_ln85_fu_454_p2 when (icmp_ln86_reg_626(0) = '1') else 
        o_fu_110;
    select_ln85_fu_460_p3 <= 
        ap_const_lv6_0 when (icmp_ln86_reg_626(0) = '1') else 
        i_fu_102;
    select_ln86_1_fu_417_p3 <= 
        ap_const_lv13_1 when (icmp_ln86_fu_289_p2(0) = '1') else 
        add_ln86_1_fu_411_p2;
    select_ln86_fu_491_p3 <= 
        add_ln86_fu_478_p2 when (and_ln85_1_reg_632(0) = '1') else 
        select_ln85_fu_460_p3;
    select_ln87_1_fu_403_p3 <= 
        ap_const_lv8_1 when (empty_fu_319_p2(0) = '1') else 
        add_ln87_1_fu_397_p2;
    select_ln87_fu_504_p3 <= 
        add_ln87_fu_498_p2 when (icmp_ln88_mid211_reg_642(0) = '1') else 
        r_mid26_fu_484_p3;
    tmp_6_fu_511_p3 <= (trunc_ln86_fu_474_p1 & ap_const_lv5_0);
    tmp_fu_529_p3 <= (add_ln89_fu_523_p2 & ap_const_lv3_0);
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_10_address0 <= zext_ln89_2_fu_547_p1(12 - 1 downto 0);
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_10_ce0 <= tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_10_ce0_local;

    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_10_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_10_ce0_local <= ap_const_logic_1;
        else 
            tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_10_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_10_d0 <= ap_const_lv4_A;
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_10_we0 <= tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_10_we0_local;

    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_10_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln88_reg_647)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln88_reg_647 = ap_const_lv3_3))) then 
            tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_10_we0_local <= ap_const_logic_1;
        else 
            tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_10_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_11_address0 <= zext_ln89_2_fu_547_p1(12 - 1 downto 0);
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_11_ce0 <= tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_11_ce0_local;

    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_11_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_11_ce0_local <= ap_const_logic_1;
        else 
            tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_11_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_11_d0 <= ap_const_lv4_A;
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_11_we0 <= tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_11_we0_local;

    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_11_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln88_reg_647)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln88_reg_647 = ap_const_lv3_4))) then 
            tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_11_we0_local <= ap_const_logic_1;
        else 
            tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_11_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_12_address0 <= zext_ln89_2_fu_547_p1(12 - 1 downto 0);
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_12_ce0 <= tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_12_ce0_local;

    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_12_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_12_ce0_local <= ap_const_logic_1;
        else 
            tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_12_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_12_d0 <= ap_const_lv4_A;
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_12_we0 <= tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_12_we0_local;

    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_12_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln88_reg_647)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln88_reg_647 = ap_const_lv3_5))) then 
            tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_12_we0_local <= ap_const_logic_1;
        else 
            tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_12_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_13_address0 <= zext_ln89_2_fu_547_p1(12 - 1 downto 0);
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_13_ce0 <= tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_13_ce0_local;

    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_13_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_13_ce0_local <= ap_const_logic_1;
        else 
            tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_13_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_13_d0 <= ap_const_lv4_A;
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_13_we0 <= tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_13_we0_local;

    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_13_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln88_reg_647)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln88_reg_647 = ap_const_lv3_6))) then 
            tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_13_we0_local <= ap_const_logic_1;
        else 
            tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_13_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_14_address0 <= zext_ln89_2_fu_547_p1(12 - 1 downto 0);
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_14_ce0 <= tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_14_ce0_local;

    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_14_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_14_ce0_local <= ap_const_logic_1;
        else 
            tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_14_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_14_d0 <= ap_const_lv4_A;
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_14_we0 <= tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_14_we0_local;

    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_14_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln88_reg_647)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln88_reg_647 = ap_const_lv3_7))) then 
            tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_14_we0_local <= ap_const_logic_1;
        else 
            tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_14_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_8_address0 <= zext_ln89_2_fu_547_p1(12 - 1 downto 0);
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_8_ce0 <= tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_8_ce0_local;

    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_8_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_8_ce0_local <= ap_const_logic_1;
        else 
            tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_8_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_8_d0 <= ap_const_lv4_A;
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_8_we0 <= tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_8_we0_local;

    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_8_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln88_reg_647)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln88_reg_647 = ap_const_lv3_1))) then 
            tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_8_we0_local <= ap_const_logic_1;
        else 
            tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_8_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_9_address0 <= zext_ln89_2_fu_547_p1(12 - 1 downto 0);
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_9_ce0 <= tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_9_ce0_local;

    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_9_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_9_ce0_local <= ap_const_logic_1;
        else 
            tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_9_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_9_d0 <= ap_const_lv4_A;
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_9_we0 <= tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_9_we0_local;

    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_9_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln88_reg_647)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln88_reg_647 = ap_const_lv3_2))) then 
            tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_9_we0_local <= ap_const_logic_1;
        else 
            tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_9_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_address0 <= zext_ln89_2_fu_547_p1(12 - 1 downto 0);
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_ce0 <= tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_ce0_local;

    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_ce0_local <= ap_const_logic_1;
        else 
            tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_d0 <= ap_const_lv4_A;
    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_we0 <= tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_we0_local;

    tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln88_reg_647)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln88_reg_647 = ap_const_lv3_0))) then 
            tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_we0_local <= ap_const_logic_1;
        else 
            tpu_layer_2_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_weights_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln86_fu_474_p1 <= select_ln85_1_fu_467_p3(4 - 1 downto 0);
    trunc_ln88_fu_369_p1 <= c_mid2_fu_361_p3(3 - 1 downto 0);
    xor_ln85_fu_295_p2 <= (icmp_ln86_fu_289_p2 xor ap_const_lv1_1);
    zext_ln89_1_fu_537_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln87_fu_504_p3),12));
    zext_ln89_2_fu_547_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln89_1_fu_541_p2),64));
    zext_ln89_fu_519_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln86_fu_491_p3),9));
end behav;
