[hls]
relative_roots=/home/dlohchab/projects/Verilog/DVCON/task_detection_tpu/yolo_backbone_1
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=conv_layer_2/VITIS_LOOP_116_1 
syn.directive.pipeline=conv_layer_1/VITIS_LOOP_19_1 
# Inferred from performance & pipeline pragmas/directives
syn.directive.loop_flatten=conv_layer_1/VITIS_LOOP_34_6  
syn.directive.loop_flatten=conv_layer_2/VITIS_LOOP_132_7 off


