// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module yolo_npu_v2_core_yolo_npu_v2_core_Pipeline_VITIS_LOOP_36_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_0_AWVALID,
        m_axi_gmem_0_AWREADY,
        m_axi_gmem_0_AWADDR,
        m_axi_gmem_0_AWID,
        m_axi_gmem_0_AWLEN,
        m_axi_gmem_0_AWSIZE,
        m_axi_gmem_0_AWBURST,
        m_axi_gmem_0_AWLOCK,
        m_axi_gmem_0_AWCACHE,
        m_axi_gmem_0_AWPROT,
        m_axi_gmem_0_AWQOS,
        m_axi_gmem_0_AWREGION,
        m_axi_gmem_0_AWUSER,
        m_axi_gmem_0_WVALID,
        m_axi_gmem_0_WREADY,
        m_axi_gmem_0_WDATA,
        m_axi_gmem_0_WSTRB,
        m_axi_gmem_0_WLAST,
        m_axi_gmem_0_WID,
        m_axi_gmem_0_WUSER,
        m_axi_gmem_0_ARVALID,
        m_axi_gmem_0_ARREADY,
        m_axi_gmem_0_ARADDR,
        m_axi_gmem_0_ARID,
        m_axi_gmem_0_ARLEN,
        m_axi_gmem_0_ARSIZE,
        m_axi_gmem_0_ARBURST,
        m_axi_gmem_0_ARLOCK,
        m_axi_gmem_0_ARCACHE,
        m_axi_gmem_0_ARPROT,
        m_axi_gmem_0_ARQOS,
        m_axi_gmem_0_ARREGION,
        m_axi_gmem_0_ARUSER,
        m_axi_gmem_0_RVALID,
        m_axi_gmem_0_RREADY,
        m_axi_gmem_0_RDATA,
        m_axi_gmem_0_RLAST,
        m_axi_gmem_0_RID,
        m_axi_gmem_0_RFIFONUM,
        m_axi_gmem_0_RUSER,
        m_axi_gmem_0_RRESP,
        m_axi_gmem_0_BVALID,
        m_axi_gmem_0_BREADY,
        m_axi_gmem_0_BRESP,
        m_axi_gmem_0_BID,
        m_axi_gmem_0_BUSER,
        cmd_out_channels,
        sp_bias_31_address0,
        sp_bias_31_ce0,
        sp_bias_31_we0,
        sp_bias_31_d0,
        sp_bias_30_address0,
        sp_bias_30_ce0,
        sp_bias_30_we0,
        sp_bias_30_d0,
        sp_bias_29_address0,
        sp_bias_29_ce0,
        sp_bias_29_we0,
        sp_bias_29_d0,
        sp_bias_28_address0,
        sp_bias_28_ce0,
        sp_bias_28_we0,
        sp_bias_28_d0,
        sp_bias_27_address0,
        sp_bias_27_ce0,
        sp_bias_27_we0,
        sp_bias_27_d0,
        sp_bias_26_address0,
        sp_bias_26_ce0,
        sp_bias_26_we0,
        sp_bias_26_d0,
        sp_bias_25_address0,
        sp_bias_25_ce0,
        sp_bias_25_we0,
        sp_bias_25_d0,
        sp_bias_24_address0,
        sp_bias_24_ce0,
        sp_bias_24_we0,
        sp_bias_24_d0,
        sp_bias_23_address0,
        sp_bias_23_ce0,
        sp_bias_23_we0,
        sp_bias_23_d0,
        sp_bias_22_address0,
        sp_bias_22_ce0,
        sp_bias_22_we0,
        sp_bias_22_d0,
        sp_bias_21_address0,
        sp_bias_21_ce0,
        sp_bias_21_we0,
        sp_bias_21_d0,
        sp_bias_20_address0,
        sp_bias_20_ce0,
        sp_bias_20_we0,
        sp_bias_20_d0,
        sp_bias_19_address0,
        sp_bias_19_ce0,
        sp_bias_19_we0,
        sp_bias_19_d0,
        sp_bias_18_address0,
        sp_bias_18_ce0,
        sp_bias_18_we0,
        sp_bias_18_d0,
        sp_bias_17_address0,
        sp_bias_17_ce0,
        sp_bias_17_we0,
        sp_bias_17_d0,
        sp_bias_16_address0,
        sp_bias_16_ce0,
        sp_bias_16_we0,
        sp_bias_16_d0,
        sp_bias_15_address0,
        sp_bias_15_ce0,
        sp_bias_15_we0,
        sp_bias_15_d0,
        sp_bias_14_address0,
        sp_bias_14_ce0,
        sp_bias_14_we0,
        sp_bias_14_d0,
        sp_bias_13_address0,
        sp_bias_13_ce0,
        sp_bias_13_we0,
        sp_bias_13_d0,
        sp_bias_12_address0,
        sp_bias_12_ce0,
        sp_bias_12_we0,
        sp_bias_12_d0,
        sp_bias_11_address0,
        sp_bias_11_ce0,
        sp_bias_11_we0,
        sp_bias_11_d0,
        sp_bias_10_address0,
        sp_bias_10_ce0,
        sp_bias_10_we0,
        sp_bias_10_d0,
        sp_bias_9_address0,
        sp_bias_9_ce0,
        sp_bias_9_we0,
        sp_bias_9_d0,
        sp_bias_8_address0,
        sp_bias_8_ce0,
        sp_bias_8_we0,
        sp_bias_8_d0,
        sp_bias_7_address0,
        sp_bias_7_ce0,
        sp_bias_7_we0,
        sp_bias_7_d0,
        sp_bias_6_address0,
        sp_bias_6_ce0,
        sp_bias_6_we0,
        sp_bias_6_d0,
        sp_bias_5_address0,
        sp_bias_5_ce0,
        sp_bias_5_we0,
        sp_bias_5_d0,
        sp_bias_4_address0,
        sp_bias_4_ce0,
        sp_bias_4_we0,
        sp_bias_4_d0,
        sp_bias_3_address0,
        sp_bias_3_ce0,
        sp_bias_3_we0,
        sp_bias_3_d0,
        sp_bias_2_address0,
        sp_bias_2_ce0,
        sp_bias_2_we0,
        sp_bias_2_d0,
        sp_bias_1_address0,
        sp_bias_1_ce0,
        sp_bias_1_we0,
        sp_bias_1_d0,
        sp_bias_address0,
        sp_bias_ce0,
        sp_bias_we0,
        sp_bias_d0,
        ddr_mem,
        sext_ln36
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_0_AWVALID;
input   m_axi_gmem_0_AWREADY;
output  [63:0] m_axi_gmem_0_AWADDR;
output  [0:0] m_axi_gmem_0_AWID;
output  [31:0] m_axi_gmem_0_AWLEN;
output  [2:0] m_axi_gmem_0_AWSIZE;
output  [1:0] m_axi_gmem_0_AWBURST;
output  [1:0] m_axi_gmem_0_AWLOCK;
output  [3:0] m_axi_gmem_0_AWCACHE;
output  [2:0] m_axi_gmem_0_AWPROT;
output  [3:0] m_axi_gmem_0_AWQOS;
output  [3:0] m_axi_gmem_0_AWREGION;
output  [0:0] m_axi_gmem_0_AWUSER;
output   m_axi_gmem_0_WVALID;
input   m_axi_gmem_0_WREADY;
output  [1023:0] m_axi_gmem_0_WDATA;
output  [127:0] m_axi_gmem_0_WSTRB;
output   m_axi_gmem_0_WLAST;
output  [0:0] m_axi_gmem_0_WID;
output  [0:0] m_axi_gmem_0_WUSER;
output   m_axi_gmem_0_ARVALID;
input   m_axi_gmem_0_ARREADY;
output  [63:0] m_axi_gmem_0_ARADDR;
output  [0:0] m_axi_gmem_0_ARID;
output  [31:0] m_axi_gmem_0_ARLEN;
output  [2:0] m_axi_gmem_0_ARSIZE;
output  [1:0] m_axi_gmem_0_ARBURST;
output  [1:0] m_axi_gmem_0_ARLOCK;
output  [3:0] m_axi_gmem_0_ARCACHE;
output  [2:0] m_axi_gmem_0_ARPROT;
output  [3:0] m_axi_gmem_0_ARQOS;
output  [3:0] m_axi_gmem_0_ARREGION;
output  [0:0] m_axi_gmem_0_ARUSER;
input   m_axi_gmem_0_RVALID;
output   m_axi_gmem_0_RREADY;
input  [1023:0] m_axi_gmem_0_RDATA;
input   m_axi_gmem_0_RLAST;
input  [0:0] m_axi_gmem_0_RID;
input  [8:0] m_axi_gmem_0_RFIFONUM;
input  [0:0] m_axi_gmem_0_RUSER;
input  [1:0] m_axi_gmem_0_RRESP;
input   m_axi_gmem_0_BVALID;
output   m_axi_gmem_0_BREADY;
input  [1:0] m_axi_gmem_0_BRESP;
input  [0:0] m_axi_gmem_0_BID;
input  [0:0] m_axi_gmem_0_BUSER;
input  [31:0] cmd_out_channels;
output  [2:0] sp_bias_31_address0;
output   sp_bias_31_ce0;
output   sp_bias_31_we0;
output  [15:0] sp_bias_31_d0;
output  [2:0] sp_bias_30_address0;
output   sp_bias_30_ce0;
output   sp_bias_30_we0;
output  [15:0] sp_bias_30_d0;
output  [2:0] sp_bias_29_address0;
output   sp_bias_29_ce0;
output   sp_bias_29_we0;
output  [15:0] sp_bias_29_d0;
output  [2:0] sp_bias_28_address0;
output   sp_bias_28_ce0;
output   sp_bias_28_we0;
output  [15:0] sp_bias_28_d0;
output  [2:0] sp_bias_27_address0;
output   sp_bias_27_ce0;
output   sp_bias_27_we0;
output  [15:0] sp_bias_27_d0;
output  [2:0] sp_bias_26_address0;
output   sp_bias_26_ce0;
output   sp_bias_26_we0;
output  [15:0] sp_bias_26_d0;
output  [2:0] sp_bias_25_address0;
output   sp_bias_25_ce0;
output   sp_bias_25_we0;
output  [15:0] sp_bias_25_d0;
output  [2:0] sp_bias_24_address0;
output   sp_bias_24_ce0;
output   sp_bias_24_we0;
output  [15:0] sp_bias_24_d0;
output  [2:0] sp_bias_23_address0;
output   sp_bias_23_ce0;
output   sp_bias_23_we0;
output  [15:0] sp_bias_23_d0;
output  [2:0] sp_bias_22_address0;
output   sp_bias_22_ce0;
output   sp_bias_22_we0;
output  [15:0] sp_bias_22_d0;
output  [2:0] sp_bias_21_address0;
output   sp_bias_21_ce0;
output   sp_bias_21_we0;
output  [15:0] sp_bias_21_d0;
output  [2:0] sp_bias_20_address0;
output   sp_bias_20_ce0;
output   sp_bias_20_we0;
output  [15:0] sp_bias_20_d0;
output  [2:0] sp_bias_19_address0;
output   sp_bias_19_ce0;
output   sp_bias_19_we0;
output  [15:0] sp_bias_19_d0;
output  [2:0] sp_bias_18_address0;
output   sp_bias_18_ce0;
output   sp_bias_18_we0;
output  [15:0] sp_bias_18_d0;
output  [2:0] sp_bias_17_address0;
output   sp_bias_17_ce0;
output   sp_bias_17_we0;
output  [15:0] sp_bias_17_d0;
output  [2:0] sp_bias_16_address0;
output   sp_bias_16_ce0;
output   sp_bias_16_we0;
output  [15:0] sp_bias_16_d0;
output  [2:0] sp_bias_15_address0;
output   sp_bias_15_ce0;
output   sp_bias_15_we0;
output  [15:0] sp_bias_15_d0;
output  [2:0] sp_bias_14_address0;
output   sp_bias_14_ce0;
output   sp_bias_14_we0;
output  [15:0] sp_bias_14_d0;
output  [2:0] sp_bias_13_address0;
output   sp_bias_13_ce0;
output   sp_bias_13_we0;
output  [15:0] sp_bias_13_d0;
output  [2:0] sp_bias_12_address0;
output   sp_bias_12_ce0;
output   sp_bias_12_we0;
output  [15:0] sp_bias_12_d0;
output  [2:0] sp_bias_11_address0;
output   sp_bias_11_ce0;
output   sp_bias_11_we0;
output  [15:0] sp_bias_11_d0;
output  [2:0] sp_bias_10_address0;
output   sp_bias_10_ce0;
output   sp_bias_10_we0;
output  [15:0] sp_bias_10_d0;
output  [2:0] sp_bias_9_address0;
output   sp_bias_9_ce0;
output   sp_bias_9_we0;
output  [15:0] sp_bias_9_d0;
output  [2:0] sp_bias_8_address0;
output   sp_bias_8_ce0;
output   sp_bias_8_we0;
output  [15:0] sp_bias_8_d0;
output  [2:0] sp_bias_7_address0;
output   sp_bias_7_ce0;
output   sp_bias_7_we0;
output  [15:0] sp_bias_7_d0;
output  [2:0] sp_bias_6_address0;
output   sp_bias_6_ce0;
output   sp_bias_6_we0;
output  [15:0] sp_bias_6_d0;
output  [2:0] sp_bias_5_address0;
output   sp_bias_5_ce0;
output   sp_bias_5_we0;
output  [15:0] sp_bias_5_d0;
output  [2:0] sp_bias_4_address0;
output   sp_bias_4_ce0;
output   sp_bias_4_we0;
output  [15:0] sp_bias_4_d0;
output  [2:0] sp_bias_3_address0;
output   sp_bias_3_ce0;
output   sp_bias_3_we0;
output  [15:0] sp_bias_3_d0;
output  [2:0] sp_bias_2_address0;
output   sp_bias_2_ce0;
output   sp_bias_2_we0;
output  [15:0] sp_bias_2_d0;
output  [2:0] sp_bias_1_address0;
output   sp_bias_1_ce0;
output   sp_bias_1_we0;
output  [15:0] sp_bias_1_d0;
output  [2:0] sp_bias_address0;
output   sp_bias_ce0;
output   sp_bias_we0;
output  [15:0] sp_bias_d0;
input  [63:0] ddr_mem;
input  [32:0] sext_ln36;

reg ap_idle;
reg m_axi_gmem_0_ARVALID;
reg m_axi_gmem_0_RREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln36_fu_672_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_blk_n_AR;
wire    ap_block_pp0_stage0_grp1;
reg    gmem_blk_n_R;
reg    ap_block_pp0_stage0_11001;
wire   [4:0] trunc_ln36_fu_684_p1;
reg   [4:0] trunc_ln36_reg_915;
reg   [4:0] trunc_ln36_reg_915_pp0_iter1_reg;
reg   [4:0] trunc_ln36_reg_915_pp0_iter2_reg;
reg   [4:0] trunc_ln36_reg_915_pp0_iter3_reg;
reg   [4:0] trunc_ln36_reg_915_pp0_iter4_reg;
reg   [4:0] trunc_ln36_reg_915_pp0_iter5_reg;
reg   [4:0] trunc_ln36_reg_915_pp0_iter6_reg;
reg   [4:0] trunc_ln36_reg_915_pp0_iter7_reg;
reg   [4:0] trunc_ln36_reg_915_pp0_iter8_reg;
reg   [2:0] lshr_ln_reg_919;
reg   [2:0] lshr_ln_reg_919_pp0_iter1_reg;
reg   [2:0] lshr_ln_reg_919_pp0_iter2_reg;
reg   [2:0] lshr_ln_reg_919_pp0_iter3_reg;
reg   [2:0] lshr_ln_reg_919_pp0_iter4_reg;
reg   [2:0] lshr_ln_reg_919_pp0_iter5_reg;
reg   [2:0] lshr_ln_reg_919_pp0_iter6_reg;
reg   [2:0] lshr_ln_reg_919_pp0_iter7_reg;
reg   [2:0] lshr_ln_reg_919_pp0_iter8_reg;
reg   [2:0] lshr_ln_reg_919_pp0_iter9_reg;
reg   [56:0] trunc_ln39_2_reg_924;
wire   [6:0] trunc_ln39_fu_732_p1;
reg   [6:0] trunc_ln39_reg_929;
reg   [6:0] trunc_ln39_reg_929_pp0_iter1_reg;
reg   [6:0] trunc_ln39_reg_929_pp0_iter2_reg;
reg   [6:0] trunc_ln39_reg_929_pp0_iter3_reg;
reg   [6:0] trunc_ln39_reg_929_pp0_iter4_reg;
reg   [6:0] trunc_ln39_reg_929_pp0_iter5_reg;
reg   [6:0] trunc_ln39_reg_929_pp0_iter6_reg;
reg   [6:0] trunc_ln39_reg_929_pp0_iter7_reg;
reg   [6:0] trunc_ln39_reg_929_pp0_iter8_reg;
reg   [6:0] trunc_ln39_reg_929_pp0_iter9_reg;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [1023:0] gmem_addr_read_reg_940;
wire   [63:0] zext_ln36_1_fu_817_p1;
wire    ap_block_pp0_stage0_grp0;
wire  signed [63:0] sext_ln39_fu_807_p1;
reg   [30:0] oc_fu_206;
wire   [30:0] add_ln36_fu_678_p2;
wire    ap_loop_init;
reg   [30:0] ap_sig_allocacmp_oc_2;
wire    ap_block_pp0_stage0;
reg    sp_bias_30_we0_local;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_predicate_pred511_state11;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
wire   [15:0] trunc_ln39_1_fu_868_p1;
reg    sp_bias_30_ce0_local;
reg    sp_bias_29_we0_local;
reg    ap_predicate_pred531_state11;
reg    sp_bias_29_ce0_local;
reg    sp_bias_28_we0_local;
reg    ap_predicate_pred545_state11;
reg    sp_bias_28_ce0_local;
reg    sp_bias_27_we0_local;
reg    ap_predicate_pred559_state11;
reg    sp_bias_27_ce0_local;
reg    sp_bias_26_we0_local;
reg    ap_predicate_pred573_state11;
reg    sp_bias_26_ce0_local;
reg    sp_bias_25_we0_local;
reg    ap_predicate_pred587_state11;
reg    sp_bias_25_ce0_local;
reg    sp_bias_24_we0_local;
reg    ap_predicate_pred601_state11;
reg    sp_bias_24_ce0_local;
reg    sp_bias_23_we0_local;
reg    ap_predicate_pred615_state11;
reg    sp_bias_23_ce0_local;
reg    sp_bias_22_we0_local;
reg    ap_predicate_pred629_state11;
reg    sp_bias_22_ce0_local;
reg    sp_bias_21_we0_local;
reg    ap_predicate_pred643_state11;
reg    sp_bias_21_ce0_local;
reg    sp_bias_20_we0_local;
reg    ap_predicate_pred657_state11;
reg    sp_bias_20_ce0_local;
reg    sp_bias_19_we0_local;
reg    ap_predicate_pred671_state11;
reg    sp_bias_19_ce0_local;
reg    sp_bias_18_we0_local;
reg    ap_predicate_pred685_state11;
reg    sp_bias_18_ce0_local;
reg    sp_bias_17_we0_local;
reg    ap_predicate_pred699_state11;
reg    sp_bias_17_ce0_local;
reg    sp_bias_16_we0_local;
reg    ap_predicate_pred713_state11;
reg    sp_bias_16_ce0_local;
reg    sp_bias_15_we0_local;
reg    ap_predicate_pred727_state11;
reg    sp_bias_15_ce0_local;
reg    sp_bias_14_we0_local;
reg    ap_predicate_pred741_state11;
reg    sp_bias_14_ce0_local;
reg    sp_bias_13_we0_local;
reg    ap_predicate_pred755_state11;
reg    sp_bias_13_ce0_local;
reg    sp_bias_12_we0_local;
reg    ap_predicate_pred769_state11;
reg    sp_bias_12_ce0_local;
reg    sp_bias_11_we0_local;
reg    ap_predicate_pred783_state11;
reg    sp_bias_11_ce0_local;
reg    sp_bias_10_we0_local;
reg    ap_predicate_pred797_state11;
reg    sp_bias_10_ce0_local;
reg    sp_bias_9_we0_local;
reg    ap_predicate_pred811_state11;
reg    sp_bias_9_ce0_local;
reg    sp_bias_8_we0_local;
reg    ap_predicate_pred825_state11;
reg    sp_bias_8_ce0_local;
reg    sp_bias_7_we0_local;
reg    ap_predicate_pred839_state11;
reg    sp_bias_7_ce0_local;
reg    sp_bias_6_we0_local;
reg    ap_predicate_pred853_state11;
reg    sp_bias_6_ce0_local;
reg    sp_bias_5_we0_local;
reg    ap_predicate_pred867_state11;
reg    sp_bias_5_ce0_local;
reg    sp_bias_4_we0_local;
reg    ap_predicate_pred881_state11;
reg    sp_bias_4_ce0_local;
reg    sp_bias_3_we0_local;
reg    ap_predicate_pred895_state11;
reg    sp_bias_3_ce0_local;
reg    sp_bias_2_we0_local;
reg    ap_predicate_pred909_state11;
reg    sp_bias_2_ce0_local;
reg    sp_bias_1_we0_local;
reg    ap_predicate_pred923_state11;
reg    sp_bias_1_ce0_local;
reg    sp_bias_we0_local;
reg    ap_predicate_pred937_state11;
reg    sp_bias_ce0_local;
reg    sp_bias_31_we0_local;
reg    ap_predicate_pred951_state11;
reg    sp_bias_31_ce0_local;
wire   [31:0] zext_ln36_fu_668_p1;
wire   [31:0] shl_ln2_fu_698_p3;
wire   [63:0] zext_ln39_fu_706_p1;
wire   [63:0] add_ln39_1_fu_710_p2;
wire  signed [63:0] sext_ln36_cast_fu_656_p1;
wire   [63:0] add_ln39_fu_716_p2;
wire   [9:0] shl_ln39_1_fu_852_p3;
wire   [1023:0] zext_ln39_1_fu_859_p1;
wire   [1023:0] lshr_ln39_fu_863_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 oc_fu_206 = 31'd0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

yolo_npu_v2_core_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter9_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln36_fu_672_p2 == 1'd1))) begin
            oc_fu_206 <= add_ln36_fu_678_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            oc_fu_206 <= 31'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        lshr_ln_reg_919 <= {{ap_sig_allocacmp_oc_2[7:5]}};
        lshr_ln_reg_919_pp0_iter1_reg <= lshr_ln_reg_919;
        trunc_ln36_reg_915 <= trunc_ln36_fu_684_p1;
        trunc_ln36_reg_915_pp0_iter1_reg <= trunc_ln36_reg_915;
        trunc_ln39_2_reg_924 <= {{add_ln39_fu_716_p2[63:7]}};
        trunc_ln39_reg_929 <= trunc_ln39_fu_732_p1;
        trunc_ln39_reg_929_pp0_iter1_reg <= trunc_ln39_reg_929;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        ap_predicate_pred511_state11 <= (trunc_ln36_reg_915_pp0_iter8_reg == 5'd30);
        ap_predicate_pred531_state11 <= (trunc_ln36_reg_915_pp0_iter8_reg == 5'd29);
        ap_predicate_pred545_state11 <= (trunc_ln36_reg_915_pp0_iter8_reg == 5'd28);
        ap_predicate_pred559_state11 <= (trunc_ln36_reg_915_pp0_iter8_reg == 5'd27);
        ap_predicate_pred573_state11 <= (trunc_ln36_reg_915_pp0_iter8_reg == 5'd26);
        ap_predicate_pred587_state11 <= (trunc_ln36_reg_915_pp0_iter8_reg == 5'd25);
        ap_predicate_pred601_state11 <= (trunc_ln36_reg_915_pp0_iter8_reg == 5'd24);
        ap_predicate_pred615_state11 <= (trunc_ln36_reg_915_pp0_iter8_reg == 5'd23);
        ap_predicate_pred629_state11 <= (trunc_ln36_reg_915_pp0_iter8_reg == 5'd22);
        ap_predicate_pred643_state11 <= (trunc_ln36_reg_915_pp0_iter8_reg == 5'd21);
        ap_predicate_pred657_state11 <= (trunc_ln36_reg_915_pp0_iter8_reg == 5'd20);
        ap_predicate_pred671_state11 <= (trunc_ln36_reg_915_pp0_iter8_reg == 5'd19);
        ap_predicate_pred685_state11 <= (trunc_ln36_reg_915_pp0_iter8_reg == 5'd18);
        ap_predicate_pred699_state11 <= (trunc_ln36_reg_915_pp0_iter8_reg == 5'd17);
        ap_predicate_pred713_state11 <= (trunc_ln36_reg_915_pp0_iter8_reg == 5'd16);
        ap_predicate_pred727_state11 <= (trunc_ln36_reg_915_pp0_iter8_reg == 5'd15);
        ap_predicate_pred741_state11 <= (trunc_ln36_reg_915_pp0_iter8_reg == 5'd14);
        ap_predicate_pred755_state11 <= (trunc_ln36_reg_915_pp0_iter8_reg == 5'd13);
        ap_predicate_pred769_state11 <= (trunc_ln36_reg_915_pp0_iter8_reg == 5'd12);
        ap_predicate_pred783_state11 <= (trunc_ln36_reg_915_pp0_iter8_reg == 5'd11);
        ap_predicate_pred797_state11 <= (trunc_ln36_reg_915_pp0_iter8_reg == 5'd10);
        ap_predicate_pred811_state11 <= (trunc_ln36_reg_915_pp0_iter8_reg == 5'd9);
        ap_predicate_pred825_state11 <= (trunc_ln36_reg_915_pp0_iter8_reg == 5'd8);
        ap_predicate_pred839_state11 <= (trunc_ln36_reg_915_pp0_iter8_reg == 5'd7);
        ap_predicate_pred853_state11 <= (trunc_ln36_reg_915_pp0_iter8_reg == 5'd6);
        ap_predicate_pred867_state11 <= (trunc_ln36_reg_915_pp0_iter8_reg == 5'd5);
        ap_predicate_pred881_state11 <= (trunc_ln36_reg_915_pp0_iter8_reg == 5'd4);
        ap_predicate_pred895_state11 <= (trunc_ln36_reg_915_pp0_iter8_reg == 5'd3);
        ap_predicate_pred909_state11 <= (trunc_ln36_reg_915_pp0_iter8_reg == 5'd2);
        ap_predicate_pred923_state11 <= (trunc_ln36_reg_915_pp0_iter8_reg == 5'd1);
        ap_predicate_pred937_state11 <= (trunc_ln36_reg_915_pp0_iter8_reg == 5'd0);
        ap_predicate_pred951_state11 <= (trunc_ln36_reg_915_pp0_iter8_reg == 5'd31);
        lshr_ln_reg_919_pp0_iter2_reg <= lshr_ln_reg_919_pp0_iter1_reg;
        lshr_ln_reg_919_pp0_iter3_reg <= lshr_ln_reg_919_pp0_iter2_reg;
        lshr_ln_reg_919_pp0_iter4_reg <= lshr_ln_reg_919_pp0_iter3_reg;
        lshr_ln_reg_919_pp0_iter5_reg <= lshr_ln_reg_919_pp0_iter4_reg;
        lshr_ln_reg_919_pp0_iter6_reg <= lshr_ln_reg_919_pp0_iter5_reg;
        lshr_ln_reg_919_pp0_iter7_reg <= lshr_ln_reg_919_pp0_iter6_reg;
        lshr_ln_reg_919_pp0_iter8_reg <= lshr_ln_reg_919_pp0_iter7_reg;
        lshr_ln_reg_919_pp0_iter9_reg <= lshr_ln_reg_919_pp0_iter8_reg;
        trunc_ln36_reg_915_pp0_iter2_reg <= trunc_ln36_reg_915_pp0_iter1_reg;
        trunc_ln36_reg_915_pp0_iter3_reg <= trunc_ln36_reg_915_pp0_iter2_reg;
        trunc_ln36_reg_915_pp0_iter4_reg <= trunc_ln36_reg_915_pp0_iter3_reg;
        trunc_ln36_reg_915_pp0_iter5_reg <= trunc_ln36_reg_915_pp0_iter4_reg;
        trunc_ln36_reg_915_pp0_iter6_reg <= trunc_ln36_reg_915_pp0_iter5_reg;
        trunc_ln36_reg_915_pp0_iter7_reg <= trunc_ln36_reg_915_pp0_iter6_reg;
        trunc_ln36_reg_915_pp0_iter8_reg <= trunc_ln36_reg_915_pp0_iter7_reg;
        trunc_ln39_reg_929_pp0_iter2_reg <= trunc_ln39_reg_929_pp0_iter1_reg;
        trunc_ln39_reg_929_pp0_iter3_reg <= trunc_ln39_reg_929_pp0_iter2_reg;
        trunc_ln39_reg_929_pp0_iter4_reg <= trunc_ln39_reg_929_pp0_iter3_reg;
        trunc_ln39_reg_929_pp0_iter5_reg <= trunc_ln39_reg_929_pp0_iter4_reg;
        trunc_ln39_reg_929_pp0_iter6_reg <= trunc_ln39_reg_929_pp0_iter5_reg;
        trunc_ln39_reg_929_pp0_iter7_reg <= trunc_ln39_reg_929_pp0_iter6_reg;
        trunc_ln39_reg_929_pp0_iter8_reg <= trunc_ln39_reg_929_pp0_iter7_reg;
        trunc_ln39_reg_929_pp0_iter9_reg <= trunc_ln39_reg_929_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        gmem_addr_read_reg_940 <= m_axi_gmem_0_RDATA;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln36_fu_672_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter9_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_oc_2 = 31'd0;
    end else begin
        ap_sig_allocacmp_oc_2 = oc_fu_206;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        gmem_blk_n_AR = m_axi_gmem_0_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        gmem_blk_n_R = m_axi_gmem_0_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m_axi_gmem_0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m_axi_gmem_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_10_ce0_local = 1'b1;
    end else begin
        sp_bias_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred797_state11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_10_we0_local = 1'b1;
    end else begin
        sp_bias_10_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_11_ce0_local = 1'b1;
    end else begin
        sp_bias_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred783_state11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_11_we0_local = 1'b1;
    end else begin
        sp_bias_11_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_12_ce0_local = 1'b1;
    end else begin
        sp_bias_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred769_state11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_12_we0_local = 1'b1;
    end else begin
        sp_bias_12_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_13_ce0_local = 1'b1;
    end else begin
        sp_bias_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred755_state11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_13_we0_local = 1'b1;
    end else begin
        sp_bias_13_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_14_ce0_local = 1'b1;
    end else begin
        sp_bias_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred741_state11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_14_we0_local = 1'b1;
    end else begin
        sp_bias_14_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_15_ce0_local = 1'b1;
    end else begin
        sp_bias_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred727_state11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_15_we0_local = 1'b1;
    end else begin
        sp_bias_15_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_16_ce0_local = 1'b1;
    end else begin
        sp_bias_16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred713_state11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_16_we0_local = 1'b1;
    end else begin
        sp_bias_16_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_17_ce0_local = 1'b1;
    end else begin
        sp_bias_17_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred699_state11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_17_we0_local = 1'b1;
    end else begin
        sp_bias_17_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_18_ce0_local = 1'b1;
    end else begin
        sp_bias_18_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred685_state11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_18_we0_local = 1'b1;
    end else begin
        sp_bias_18_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_19_ce0_local = 1'b1;
    end else begin
        sp_bias_19_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred671_state11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_19_we0_local = 1'b1;
    end else begin
        sp_bias_19_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_1_ce0_local = 1'b1;
    end else begin
        sp_bias_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred923_state11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_1_we0_local = 1'b1;
    end else begin
        sp_bias_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_20_ce0_local = 1'b1;
    end else begin
        sp_bias_20_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred657_state11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_20_we0_local = 1'b1;
    end else begin
        sp_bias_20_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_21_ce0_local = 1'b1;
    end else begin
        sp_bias_21_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred643_state11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_21_we0_local = 1'b1;
    end else begin
        sp_bias_21_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_22_ce0_local = 1'b1;
    end else begin
        sp_bias_22_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred629_state11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_22_we0_local = 1'b1;
    end else begin
        sp_bias_22_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_23_ce0_local = 1'b1;
    end else begin
        sp_bias_23_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred615_state11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_23_we0_local = 1'b1;
    end else begin
        sp_bias_23_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_24_ce0_local = 1'b1;
    end else begin
        sp_bias_24_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred601_state11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_24_we0_local = 1'b1;
    end else begin
        sp_bias_24_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_25_ce0_local = 1'b1;
    end else begin
        sp_bias_25_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred587_state11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_25_we0_local = 1'b1;
    end else begin
        sp_bias_25_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_26_ce0_local = 1'b1;
    end else begin
        sp_bias_26_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred573_state11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_26_we0_local = 1'b1;
    end else begin
        sp_bias_26_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_27_ce0_local = 1'b1;
    end else begin
        sp_bias_27_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred559_state11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_27_we0_local = 1'b1;
    end else begin
        sp_bias_27_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_28_ce0_local = 1'b1;
    end else begin
        sp_bias_28_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred545_state11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_28_we0_local = 1'b1;
    end else begin
        sp_bias_28_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_29_ce0_local = 1'b1;
    end else begin
        sp_bias_29_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred531_state11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_29_we0_local = 1'b1;
    end else begin
        sp_bias_29_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_2_ce0_local = 1'b1;
    end else begin
        sp_bias_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred909_state11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_2_we0_local = 1'b1;
    end else begin
        sp_bias_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_30_ce0_local = 1'b1;
    end else begin
        sp_bias_30_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred511_state11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_30_we0_local = 1'b1;
    end else begin
        sp_bias_30_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_31_ce0_local = 1'b1;
    end else begin
        sp_bias_31_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred951_state11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_31_we0_local = 1'b1;
    end else begin
        sp_bias_31_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_3_ce0_local = 1'b1;
    end else begin
        sp_bias_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred895_state11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_3_we0_local = 1'b1;
    end else begin
        sp_bias_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_4_ce0_local = 1'b1;
    end else begin
        sp_bias_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred881_state11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_4_we0_local = 1'b1;
    end else begin
        sp_bias_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_5_ce0_local = 1'b1;
    end else begin
        sp_bias_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred867_state11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_5_we0_local = 1'b1;
    end else begin
        sp_bias_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_6_ce0_local = 1'b1;
    end else begin
        sp_bias_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred853_state11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_6_we0_local = 1'b1;
    end else begin
        sp_bias_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_7_ce0_local = 1'b1;
    end else begin
        sp_bias_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred839_state11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_7_we0_local = 1'b1;
    end else begin
        sp_bias_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_8_ce0_local = 1'b1;
    end else begin
        sp_bias_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred825_state11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_8_we0_local = 1'b1;
    end else begin
        sp_bias_8_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_9_ce0_local = 1'b1;
    end else begin
        sp_bias_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred811_state11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_9_we0_local = 1'b1;
    end else begin
        sp_bias_9_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_ce0_local = 1'b1;
    end else begin
        sp_bias_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_pred937_state11 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        sp_bias_we0_local = 1'b1;
    end else begin
        sp_bias_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln36_fu_678_p2 = (ap_sig_allocacmp_oc_2 + 31'd1);

assign add_ln39_1_fu_710_p2 = (zext_ln39_fu_706_p1 + ddr_mem);

assign add_ln39_fu_716_p2 = ($signed(add_ln39_1_fu_710_p2) + $signed(sext_ln36_cast_fu_656_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((m_axi_gmem_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1)) | ((m_axi_gmem_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((m_axi_gmem_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1)) | ((m_axi_gmem_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((m_axi_gmem_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b1)) | ((m_axi_gmem_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln36_fu_672_p2 = (($signed(zext_ln36_fu_668_p1) < $signed(cmd_out_channels)) ? 1'b1 : 1'b0);

assign lshr_ln39_fu_863_p2 = gmem_addr_read_reg_940 >> zext_ln39_1_fu_859_p1;

assign m_axi_gmem_0_ARADDR = sext_ln39_fu_807_p1;

assign m_axi_gmem_0_ARBURST = 2'd0;

assign m_axi_gmem_0_ARCACHE = 4'd0;

assign m_axi_gmem_0_ARID = 1'd0;

assign m_axi_gmem_0_ARLEN = 64'd1;

assign m_axi_gmem_0_ARLOCK = 2'd0;

assign m_axi_gmem_0_ARPROT = 3'd0;

assign m_axi_gmem_0_ARQOS = 4'd0;

assign m_axi_gmem_0_ARREGION = 4'd0;

assign m_axi_gmem_0_ARSIZE = 3'd0;

assign m_axi_gmem_0_ARUSER = 1'd0;

assign m_axi_gmem_0_AWADDR = 64'd0;

assign m_axi_gmem_0_AWBURST = 2'd0;

assign m_axi_gmem_0_AWCACHE = 4'd0;

assign m_axi_gmem_0_AWID = 1'd0;

assign m_axi_gmem_0_AWLEN = 32'd0;

assign m_axi_gmem_0_AWLOCK = 2'd0;

assign m_axi_gmem_0_AWPROT = 3'd0;

assign m_axi_gmem_0_AWQOS = 4'd0;

assign m_axi_gmem_0_AWREGION = 4'd0;

assign m_axi_gmem_0_AWSIZE = 3'd0;

assign m_axi_gmem_0_AWUSER = 1'd0;

assign m_axi_gmem_0_AWVALID = 1'b0;

assign m_axi_gmem_0_BREADY = 1'b0;

assign m_axi_gmem_0_WDATA = 1024'd0;

assign m_axi_gmem_0_WID = 1'd0;

assign m_axi_gmem_0_WLAST = 1'b0;

assign m_axi_gmem_0_WSTRB = 128'd0;

assign m_axi_gmem_0_WUSER = 1'd0;

assign m_axi_gmem_0_WVALID = 1'b0;

assign sext_ln36_cast_fu_656_p1 = $signed(sext_ln36);

assign sext_ln39_fu_807_p1 = $signed(trunc_ln39_2_reg_924);

assign shl_ln2_fu_698_p3 = {{ap_sig_allocacmp_oc_2}, {1'd0}};

assign shl_ln39_1_fu_852_p3 = {{trunc_ln39_reg_929_pp0_iter9_reg}, {3'd0}};

assign sp_bias_10_address0 = zext_ln36_1_fu_817_p1;

assign sp_bias_10_ce0 = sp_bias_10_ce0_local;

assign sp_bias_10_d0 = trunc_ln39_1_fu_868_p1;

assign sp_bias_10_we0 = sp_bias_10_we0_local;

assign sp_bias_11_address0 = zext_ln36_1_fu_817_p1;

assign sp_bias_11_ce0 = sp_bias_11_ce0_local;

assign sp_bias_11_d0 = trunc_ln39_1_fu_868_p1;

assign sp_bias_11_we0 = sp_bias_11_we0_local;

assign sp_bias_12_address0 = zext_ln36_1_fu_817_p1;

assign sp_bias_12_ce0 = sp_bias_12_ce0_local;

assign sp_bias_12_d0 = trunc_ln39_1_fu_868_p1;

assign sp_bias_12_we0 = sp_bias_12_we0_local;

assign sp_bias_13_address0 = zext_ln36_1_fu_817_p1;

assign sp_bias_13_ce0 = sp_bias_13_ce0_local;

assign sp_bias_13_d0 = trunc_ln39_1_fu_868_p1;

assign sp_bias_13_we0 = sp_bias_13_we0_local;

assign sp_bias_14_address0 = zext_ln36_1_fu_817_p1;

assign sp_bias_14_ce0 = sp_bias_14_ce0_local;

assign sp_bias_14_d0 = trunc_ln39_1_fu_868_p1;

assign sp_bias_14_we0 = sp_bias_14_we0_local;

assign sp_bias_15_address0 = zext_ln36_1_fu_817_p1;

assign sp_bias_15_ce0 = sp_bias_15_ce0_local;

assign sp_bias_15_d0 = trunc_ln39_1_fu_868_p1;

assign sp_bias_15_we0 = sp_bias_15_we0_local;

assign sp_bias_16_address0 = zext_ln36_1_fu_817_p1;

assign sp_bias_16_ce0 = sp_bias_16_ce0_local;

assign sp_bias_16_d0 = trunc_ln39_1_fu_868_p1;

assign sp_bias_16_we0 = sp_bias_16_we0_local;

assign sp_bias_17_address0 = zext_ln36_1_fu_817_p1;

assign sp_bias_17_ce0 = sp_bias_17_ce0_local;

assign sp_bias_17_d0 = trunc_ln39_1_fu_868_p1;

assign sp_bias_17_we0 = sp_bias_17_we0_local;

assign sp_bias_18_address0 = zext_ln36_1_fu_817_p1;

assign sp_bias_18_ce0 = sp_bias_18_ce0_local;

assign sp_bias_18_d0 = trunc_ln39_1_fu_868_p1;

assign sp_bias_18_we0 = sp_bias_18_we0_local;

assign sp_bias_19_address0 = zext_ln36_1_fu_817_p1;

assign sp_bias_19_ce0 = sp_bias_19_ce0_local;

assign sp_bias_19_d0 = trunc_ln39_1_fu_868_p1;

assign sp_bias_19_we0 = sp_bias_19_we0_local;

assign sp_bias_1_address0 = zext_ln36_1_fu_817_p1;

assign sp_bias_1_ce0 = sp_bias_1_ce0_local;

assign sp_bias_1_d0 = trunc_ln39_1_fu_868_p1;

assign sp_bias_1_we0 = sp_bias_1_we0_local;

assign sp_bias_20_address0 = zext_ln36_1_fu_817_p1;

assign sp_bias_20_ce0 = sp_bias_20_ce0_local;

assign sp_bias_20_d0 = trunc_ln39_1_fu_868_p1;

assign sp_bias_20_we0 = sp_bias_20_we0_local;

assign sp_bias_21_address0 = zext_ln36_1_fu_817_p1;

assign sp_bias_21_ce0 = sp_bias_21_ce0_local;

assign sp_bias_21_d0 = trunc_ln39_1_fu_868_p1;

assign sp_bias_21_we0 = sp_bias_21_we0_local;

assign sp_bias_22_address0 = zext_ln36_1_fu_817_p1;

assign sp_bias_22_ce0 = sp_bias_22_ce0_local;

assign sp_bias_22_d0 = trunc_ln39_1_fu_868_p1;

assign sp_bias_22_we0 = sp_bias_22_we0_local;

assign sp_bias_23_address0 = zext_ln36_1_fu_817_p1;

assign sp_bias_23_ce0 = sp_bias_23_ce0_local;

assign sp_bias_23_d0 = trunc_ln39_1_fu_868_p1;

assign sp_bias_23_we0 = sp_bias_23_we0_local;

assign sp_bias_24_address0 = zext_ln36_1_fu_817_p1;

assign sp_bias_24_ce0 = sp_bias_24_ce0_local;

assign sp_bias_24_d0 = trunc_ln39_1_fu_868_p1;

assign sp_bias_24_we0 = sp_bias_24_we0_local;

assign sp_bias_25_address0 = zext_ln36_1_fu_817_p1;

assign sp_bias_25_ce0 = sp_bias_25_ce0_local;

assign sp_bias_25_d0 = trunc_ln39_1_fu_868_p1;

assign sp_bias_25_we0 = sp_bias_25_we0_local;

assign sp_bias_26_address0 = zext_ln36_1_fu_817_p1;

assign sp_bias_26_ce0 = sp_bias_26_ce0_local;

assign sp_bias_26_d0 = trunc_ln39_1_fu_868_p1;

assign sp_bias_26_we0 = sp_bias_26_we0_local;

assign sp_bias_27_address0 = zext_ln36_1_fu_817_p1;

assign sp_bias_27_ce0 = sp_bias_27_ce0_local;

assign sp_bias_27_d0 = trunc_ln39_1_fu_868_p1;

assign sp_bias_27_we0 = sp_bias_27_we0_local;

assign sp_bias_28_address0 = zext_ln36_1_fu_817_p1;

assign sp_bias_28_ce0 = sp_bias_28_ce0_local;

assign sp_bias_28_d0 = trunc_ln39_1_fu_868_p1;

assign sp_bias_28_we0 = sp_bias_28_we0_local;

assign sp_bias_29_address0 = zext_ln36_1_fu_817_p1;

assign sp_bias_29_ce0 = sp_bias_29_ce0_local;

assign sp_bias_29_d0 = trunc_ln39_1_fu_868_p1;

assign sp_bias_29_we0 = sp_bias_29_we0_local;

assign sp_bias_2_address0 = zext_ln36_1_fu_817_p1;

assign sp_bias_2_ce0 = sp_bias_2_ce0_local;

assign sp_bias_2_d0 = trunc_ln39_1_fu_868_p1;

assign sp_bias_2_we0 = sp_bias_2_we0_local;

assign sp_bias_30_address0 = zext_ln36_1_fu_817_p1;

assign sp_bias_30_ce0 = sp_bias_30_ce0_local;

assign sp_bias_30_d0 = trunc_ln39_1_fu_868_p1;

assign sp_bias_30_we0 = sp_bias_30_we0_local;

assign sp_bias_31_address0 = zext_ln36_1_fu_817_p1;

assign sp_bias_31_ce0 = sp_bias_31_ce0_local;

assign sp_bias_31_d0 = trunc_ln39_1_fu_868_p1;

assign sp_bias_31_we0 = sp_bias_31_we0_local;

assign sp_bias_3_address0 = zext_ln36_1_fu_817_p1;

assign sp_bias_3_ce0 = sp_bias_3_ce0_local;

assign sp_bias_3_d0 = trunc_ln39_1_fu_868_p1;

assign sp_bias_3_we0 = sp_bias_3_we0_local;

assign sp_bias_4_address0 = zext_ln36_1_fu_817_p1;

assign sp_bias_4_ce0 = sp_bias_4_ce0_local;

assign sp_bias_4_d0 = trunc_ln39_1_fu_868_p1;

assign sp_bias_4_we0 = sp_bias_4_we0_local;

assign sp_bias_5_address0 = zext_ln36_1_fu_817_p1;

assign sp_bias_5_ce0 = sp_bias_5_ce0_local;

assign sp_bias_5_d0 = trunc_ln39_1_fu_868_p1;

assign sp_bias_5_we0 = sp_bias_5_we0_local;

assign sp_bias_6_address0 = zext_ln36_1_fu_817_p1;

assign sp_bias_6_ce0 = sp_bias_6_ce0_local;

assign sp_bias_6_d0 = trunc_ln39_1_fu_868_p1;

assign sp_bias_6_we0 = sp_bias_6_we0_local;

assign sp_bias_7_address0 = zext_ln36_1_fu_817_p1;

assign sp_bias_7_ce0 = sp_bias_7_ce0_local;

assign sp_bias_7_d0 = trunc_ln39_1_fu_868_p1;

assign sp_bias_7_we0 = sp_bias_7_we0_local;

assign sp_bias_8_address0 = zext_ln36_1_fu_817_p1;

assign sp_bias_8_ce0 = sp_bias_8_ce0_local;

assign sp_bias_8_d0 = trunc_ln39_1_fu_868_p1;

assign sp_bias_8_we0 = sp_bias_8_we0_local;

assign sp_bias_9_address0 = zext_ln36_1_fu_817_p1;

assign sp_bias_9_ce0 = sp_bias_9_ce0_local;

assign sp_bias_9_d0 = trunc_ln39_1_fu_868_p1;

assign sp_bias_9_we0 = sp_bias_9_we0_local;

assign sp_bias_address0 = zext_ln36_1_fu_817_p1;

assign sp_bias_ce0 = sp_bias_ce0_local;

assign sp_bias_d0 = trunc_ln39_1_fu_868_p1;

assign sp_bias_we0 = sp_bias_we0_local;

assign trunc_ln36_fu_684_p1 = ap_sig_allocacmp_oc_2[4:0];

assign trunc_ln39_1_fu_868_p1 = lshr_ln39_fu_863_p2[15:0];

assign trunc_ln39_fu_732_p1 = add_ln39_fu_716_p2[6:0];

assign zext_ln36_1_fu_817_p1 = lshr_ln_reg_919_pp0_iter9_reg;

assign zext_ln36_fu_668_p1 = ap_sig_allocacmp_oc_2;

assign zext_ln39_1_fu_859_p1 = shl_ln39_1_fu_852_p3;

assign zext_ln39_fu_706_p1 = shl_ln2_fu_698_p3;

endmodule //yolo_npu_v2_core_yolo_npu_v2_core_Pipeline_VITIS_LOOP_36_2
