// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module task_detection_accel_task_detection_accel_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_23_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        weights_1_address0,
        weights_1_ce0,
        weights_1_we0,
        weights_1_d0,
        bias_1_address0,
        bias_1_ce0,
        bias_1_we0,
        bias_1_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [15:0] weights_1_address0;
output   weights_1_ce0;
output   weights_1_we0;
output  [31:0] weights_1_d0;
output  [7:0] bias_1_address0;
output   bias_1_ce0;
output   bias_1_we0;
output  [31:0] bias_1_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln19_fu_104_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [15:0] add_ln25_fu_175_p2;
reg   [15:0] add_ln25_reg_233;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln19_fu_156_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln25_1_fu_202_p1;
reg   [7:0] i_1_fu_46;
wire   [7:0] add_ln23_fu_181_p2;
wire    ap_loop_init;
reg   [8:0] o_fu_50;
wire   [8:0] select_ln19_1_fu_142_p3;
reg   [15:0] indvar_flatten_fu_54;
wire   [15:0] add_ln19_1_fu_110_p2;
reg    bias_1_we0_local;
wire   [0:0] first_iter_0_fu_150_p2;
reg    bias_1_ce0_local;
reg    weights_1_we0_local;
reg    weights_1_ce0_local;
wire   [0:0] icmp_ln23_fu_128_p2;
wire   [8:0] add_ln19_fu_122_p2;
wire   [7:0] select_ln19_fu_134_p3;
wire   [8:0] mul_ln21_fu_165_p0;
wire   [8:0] mul_ln21_fu_165_p1;
wire   [15:0] mul_ln21_fu_165_p2;
wire   [15:0] zext_ln25_fu_171_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [15:0] mul_ln21_fu_165_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 i_1_fu_46 = 8'd0;
#0 o_fu_50 = 9'd0;
#0 indvar_flatten_fu_54 = 16'd0;
#0 ap_done_reg = 1'b0;
end

task_detection_accel_mul_9ns_9ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 16 ))
mul_9ns_9ns_16_1_1_U4(
    .din0(mul_ln21_fu_165_p0),
    .din1(mul_ln21_fu_165_p1),
    .dout(mul_ln21_fu_165_p2)
);

task_detection_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_1_fu_46 <= 8'd0;
        end else if (((icmp_ln19_fu_104_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_1_fu_46 <= add_ln23_fu_181_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_54 <= 16'd0;
        end else if (((icmp_ln19_fu_104_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten_fu_54 <= add_ln19_1_fu_110_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            o_fu_50 <= 9'd0;
        end else if (((icmp_ln19_fu_104_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            o_fu_50 <= select_ln19_1_fu_142_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln25_reg_233 <= add_ln25_fu_175_p2;
    end
end

always @ (*) begin
    if (((icmp_ln19_fu_104_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bias_1_ce0_local = 1'b1;
    end else begin
        bias_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln19_fu_104_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (first_iter_0_fu_150_p2 == 1'd1))) begin
        bias_1_we0_local = 1'b1;
    end else begin
        bias_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        weights_1_ce0_local = 1'b1;
    end else begin
        weights_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        weights_1_we0_local = 1'b1;
    end else begin
        weights_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln19_1_fu_110_p2 = (indvar_flatten_fu_54 + 16'd1);

assign add_ln19_fu_122_p2 = (o_fu_50 + 9'd1);

assign add_ln23_fu_181_p2 = (select_ln19_fu_134_p3 + 8'd1);

assign add_ln25_fu_175_p2 = (mul_ln21_fu_165_p2 + zext_ln25_fu_171_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign bias_1_address0 = zext_ln19_fu_156_p1;

assign bias_1_ce0 = bias_1_ce0_local;

assign bias_1_d0 = 32'd0;

assign bias_1_we0 = bias_1_we0_local;

assign first_iter_0_fu_150_p2 = ((select_ln19_fu_134_p3 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln19_fu_104_p2 = ((indvar_flatten_fu_54 == 16'd46080) ? 1'b1 : 1'b0);

assign icmp_ln23_fu_128_p2 = ((i_1_fu_46 == 8'd180) ? 1'b1 : 1'b0);

assign mul_ln21_fu_165_p0 = mul_ln21_fu_165_p00;

assign mul_ln21_fu_165_p00 = select_ln19_1_fu_142_p3;

assign mul_ln21_fu_165_p1 = 16'd180;

assign select_ln19_1_fu_142_p3 = ((icmp_ln23_fu_128_p2[0:0] == 1'b1) ? add_ln19_fu_122_p2 : o_fu_50);

assign select_ln19_fu_134_p3 = ((icmp_ln23_fu_128_p2[0:0] == 1'b1) ? 8'd0 : i_1_fu_46);

assign weights_1_address0 = zext_ln25_1_fu_202_p1;

assign weights_1_ce0 = weights_1_ce0_local;

assign weights_1_d0 = 32'd1008981770;

assign weights_1_we0 = weights_1_we0_local;

assign zext_ln19_fu_156_p1 = select_ln19_1_fu_142_p3;

assign zext_ln25_1_fu_202_p1 = add_ln25_reg_233;

assign zext_ln25_fu_171_p1 = select_ln19_fu_134_p3;

endmodule //task_detection_accel_task_detection_accel_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_23_2
