// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module task_detection_accel_task_detection_accel_Pipeline_VITIS_LOOP_32_3_VITIS_LOOP_38_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_buf_address0,
        in_buf_ce0,
        in_buf_q0,
        l1_address0,
        l1_ce0,
        l1_we0,
        l1_d0,
        weights_1_address0,
        weights_1_ce0,
        weights_1_q0,
        bias_1_address0,
        bias_1_ce0,
        bias_1_q0,
        grp_fu_385_p_din0,
        grp_fu_385_p_din1,
        grp_fu_385_p_dout0,
        grp_fu_385_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] in_buf_address0;
output   in_buf_ce0;
input  [31:0] in_buf_q0;
output  [7:0] l1_address0;
output   l1_ce0;
output   l1_we0;
output  [31:0] l1_d0;
output  [15:0] weights_1_address0;
output   weights_1_ce0;
input  [31:0] weights_1_q0;
output  [7:0] bias_1_address0;
output   bias_1_ce0;
input  [31:0] bias_1_q0;
output  [31:0] grp_fu_385_p_din0;
output  [31:0] grp_fu_385_p_din1;
input  [31:0] grp_fu_385_p_dout0;
output   grp_fu_385_p_ce;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln32_fu_141_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [8:0] select_ln32_1_fu_179_p3;
reg   [8:0] select_ln32_1_reg_301;
reg   [8:0] select_ln32_1_reg_301_pp0_iter2_reg;
wire   [0:0] first_iter_1_fu_187_p2;
reg   [0:0] first_iter_1_reg_306;
reg   [0:0] first_iter_1_reg_306_pp0_iter2_reg;
reg   [0:0] first_iter_1_reg_306_pp0_iter3_reg;
wire   [0:0] icmp_ln38_1_fu_229_p2;
reg   [0:0] icmp_ln38_1_reg_320;
reg   [0:0] icmp_ln38_1_reg_320_pp0_iter2_reg;
reg   [0:0] icmp_ln38_1_reg_320_pp0_iter3_reg;
reg   [0:0] icmp_ln38_1_reg_320_pp0_iter4_reg;
reg   [0:0] icmp_ln38_1_reg_320_pp0_iter5_reg;
reg   [7:0] l1_addr_reg_339;
reg   [7:0] l1_addr_reg_339_pp0_iter4_reg;
reg   [7:0] l1_addr_reg_339_pp0_iter5_reg;
reg   [31:0] mul_i_reg_344;
wire   [31:0] acc_2_fu_113_p2;
reg   [31:0] acc_2_reg_349;
wire   [63:0] zext_ln41_1_fu_218_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln38_fu_203_p1;
wire   [63:0] zext_ln32_fu_250_p1;
reg   [7:0] i_fu_46;
wire   [7:0] add_ln38_fu_223_p2;
wire    ap_loop_init;
reg   [8:0] o_fu_50;
reg   [15:0] indvar_flatten9_fu_54;
wire   [15:0] add_ln32_1_fu_147_p2;
reg   [31:0] acc_1_fu_58;
reg    in_buf_ce0_local;
reg    weights_1_ce0_local;
reg    bias_1_ce0_local;
reg    l1_we0_local;
reg    l1_ce0_local;
wire   [0:0] icmp_ln38_fu_165_p2;
wire   [8:0] add_ln32_fu_159_p2;
wire   [7:0] select_ln32_fu_171_p3;
wire   [8:0] mul_ln36_fu_197_p0;
wire   [8:0] mul_ln36_fu_197_p1;
wire   [15:0] mul_ln36_fu_197_p2;
wire   [15:0] zext_ln41_fu_208_p1;
wire   [15:0] add_ln41_fu_212_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [15:0] mul_ln36_fu_197_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 i_fu_46 = 8'd0;
#0 o_fu_50 = 9'd0;
#0 indvar_flatten9_fu_54 = 16'd0;
#0 acc_1_fu_58 = 32'd0;
#0 ap_done_reg = 1'b0;
end

task_detection_accel_fadd_32ns_32ns_32_1_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_1_full_dsp_1_U8(
    .din0(acc_1_fu_58),
    .din1(mul_i_reg_344),
    .dout(acc_2_fu_113_p2)
);

task_detection_accel_mul_9ns_9ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 16 ))
mul_9ns_9ns_16_1_1_U10(
    .din0(mul_ln36_fu_197_p0),
    .din1(mul_ln36_fu_197_p1),
    .dout(mul_ln36_fu_197_p2)
);

task_detection_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_enable_reg_pp0_iter4 == 1'b1) & (first_iter_1_reg_306_pp0_iter3_reg == 1'd1))) begin
            acc_1_fu_58 <= bias_1_q0;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            acc_1_fu_58 <= acc_2_fu_113_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_46 <= 8'd0;
        end else if (((icmp_ln32_fu_141_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_fu_46 <= add_ln38_fu_223_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten9_fu_54 <= 16'd0;
        end else if (((icmp_ln32_fu_141_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten9_fu_54 <= add_ln32_1_fu_147_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            o_fu_50 <= 9'd0;
        end else if (((icmp_ln32_fu_141_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            o_fu_50 <= select_ln32_1_fu_179_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        acc_2_reg_349 <= acc_2_fu_113_p2;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        first_iter_1_reg_306_pp0_iter2_reg <= first_iter_1_reg_306;
        first_iter_1_reg_306_pp0_iter3_reg <= first_iter_1_reg_306_pp0_iter2_reg;
        icmp_ln38_1_reg_320_pp0_iter2_reg <= icmp_ln38_1_reg_320;
        icmp_ln38_1_reg_320_pp0_iter3_reg <= icmp_ln38_1_reg_320_pp0_iter2_reg;
        icmp_ln38_1_reg_320_pp0_iter4_reg <= icmp_ln38_1_reg_320_pp0_iter3_reg;
        icmp_ln38_1_reg_320_pp0_iter5_reg <= icmp_ln38_1_reg_320_pp0_iter4_reg;
        l1_addr_reg_339 <= zext_ln32_fu_250_p1;
        l1_addr_reg_339_pp0_iter4_reg <= l1_addr_reg_339;
        l1_addr_reg_339_pp0_iter5_reg <= l1_addr_reg_339_pp0_iter4_reg;
        mul_i_reg_344 <= grp_fu_385_p_dout0;
        select_ln32_1_reg_301_pp0_iter2_reg <= select_ln32_1_reg_301;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        first_iter_1_reg_306 <= first_iter_1_fu_187_p2;
        icmp_ln38_1_reg_320 <= icmp_ln38_1_fu_229_p2;
        select_ln32_1_reg_301 <= select_ln32_1_fu_179_p3;
    end
end

always @ (*) begin
    if (((icmp_ln32_fu_141_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        bias_1_ce0_local = 1'b1;
    end else begin
        bias_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_buf_ce0_local = 1'b1;
    end else begin
        in_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        l1_ce0_local = 1'b1;
    end else begin
        l1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln38_1_reg_320_pp0_iter5_reg == 1'd1))) begin
        l1_we0_local = 1'b1;
    end else begin
        l1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_1_ce0_local = 1'b1;
    end else begin
        weights_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln32_1_fu_147_p2 = (indvar_flatten9_fu_54 + 16'd1);

assign add_ln32_fu_159_p2 = (o_fu_50 + 9'd1);

assign add_ln38_fu_223_p2 = (select_ln32_fu_171_p3 + 8'd1);

assign add_ln41_fu_212_p2 = (mul_ln36_fu_197_p2 + zext_ln41_fu_208_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign bias_1_address0 = zext_ln32_fu_250_p1;

assign bias_1_ce0 = bias_1_ce0_local;

assign first_iter_1_fu_187_p2 = ((select_ln32_fu_171_p3 == 8'd0) ? 1'b1 : 1'b0);

assign grp_fu_385_p_ce = 1'b1;

assign grp_fu_385_p_din0 = in_buf_q0;

assign grp_fu_385_p_din1 = weights_1_q0;

assign icmp_ln32_fu_141_p2 = ((indvar_flatten9_fu_54 == 16'd46080) ? 1'b1 : 1'b0);

assign icmp_ln38_1_fu_229_p2 = ((add_ln38_fu_223_p2 == 8'd180) ? 1'b1 : 1'b0);

assign icmp_ln38_fu_165_p2 = ((i_fu_46 == 8'd180) ? 1'b1 : 1'b0);

assign in_buf_address0 = zext_ln38_fu_203_p1;

assign in_buf_ce0 = in_buf_ce0_local;

assign l1_address0 = l1_addr_reg_339_pp0_iter5_reg;

assign l1_ce0 = l1_ce0_local;

assign l1_d0 = acc_2_reg_349;

assign l1_we0 = l1_we0_local;

assign mul_ln36_fu_197_p0 = mul_ln36_fu_197_p00;

assign mul_ln36_fu_197_p00 = select_ln32_1_fu_179_p3;

assign mul_ln36_fu_197_p1 = 16'd180;

assign select_ln32_1_fu_179_p3 = ((icmp_ln38_fu_165_p2[0:0] == 1'b1) ? add_ln32_fu_159_p2 : o_fu_50);

assign select_ln32_fu_171_p3 = ((icmp_ln38_fu_165_p2[0:0] == 1'b1) ? 8'd0 : i_fu_46);

assign weights_1_address0 = zext_ln41_1_fu_218_p1;

assign weights_1_ce0 = weights_1_ce0_local;

assign zext_ln32_fu_250_p1 = select_ln32_1_reg_301_pp0_iter2_reg;

assign zext_ln38_fu_203_p1 = select_ln32_fu_171_p3;

assign zext_ln41_1_fu_218_p1 = add_ln41_fu_212_p2;

assign zext_ln41_fu_208_p1 = select_ln32_fu_171_p3;

endmodule //task_detection_accel_task_detection_accel_Pipeline_VITIS_LOOP_32_3_VITIS_LOOP_38_4
