[hls]
relative_roots=/home/dlohchab/projects/Verilog/DVCON/task_detection_tpu/tpu_tile_8x8
# Inferred from performance & pipeline pragmas/directives
syn.directive.loop_flatten=matmul_tile_16x16/ROW_LOOP  


