# Inferred from syn.compile.pipeline_loops=64
set_directive_pipeline tpu_layer_1/VITIS_LOOP_46_1
set_directive_pipeline tpu_layer_1/VITIS_LOOP_47_2
set_directive_pipeline tpu_layer_1/VITIS_LOOP_53_3
set_directive_pipeline tpu_layer_1/VITIS_LOOP_57_7
set_directive_pipeline tpu_layer_1/VITIS_LOOP_72_12
set_directive_pipeline tpu_layer_1/VITIS_LOOP_66_10
set_directive_pipeline tpu_layer_1/anonymous
set_directive_pipeline task_detection_accel/VITIS_LOOP_170_1
set_directive_pipeline task_detection_accel/VITIS_LOOP_84_1
set_directive_pipeline task_detection_accel/VITIS_LOOP_88_5
set_directive_pipeline task_detection_accel/VITIS_LOOP_103_10
set_directive_pipeline task_detection_accel/VITIS_LOOP_97_8
set_directive_pipeline task_detection_accel/anonymous
set_directive_pipeline task_detection_accel/VITIS_LOOP_115_1
set_directive_pipeline task_detection_accel/VITIS_LOOP_119_5
set_directive_pipeline task_detection_accel/VITIS_LOOP_134_10
set_directive_pipeline task_detection_accel/VITIS_LOOP_128_8
set_directive_pipeline task_detection_accel/anonymous
set_directive_pipeline task_detection_accel/VITIS_LOOP_146_1
# Inferred from Performance Budgeter performance directives
set_directive_loop_flatten tpu_layer_1/VITIS_LOOP_56_6
set_directive_loop_flatten tpu_layer_1/VITIS_LOOP_55_5
set_directive_loop_flatten tpu_layer_1/VITIS_LOOP_54_4
set_directive_loop_flatten task_detection_accel/VITIS_LOOP_87_4
set_directive_loop_flatten task_detection_accel/VITIS_LOOP_86_3
set_directive_loop_flatten task_detection_accel/VITIS_LOOP_85_2
set_directive_loop_flatten task_detection_accel/VITIS_LOOP_118_4
set_directive_loop_flatten task_detection_accel/VITIS_LOOP_117_3
set_directive_loop_flatten task_detection_accel/VITIS_LOOP_116_2
# Inferred from performance & pipeline pragmas/directives
set_directive_inline systolic_8x8
set_directive_array_partition tpu_layer_1/w_tile -dim=1 -type=complete w_tile
set_directive_array_partition task_detection_accel/w_tile.i -dim=1 -type=complete w_tile.i
set_directive_array_partition task_detection_accel/w_tile.i33 -dim=1 -type=complete w_tile.i33
