# Inferred from syn.compile.pipeline_loops=64
set_directive_pipeline scalar_layer_4/VITIS_LOOP_372_1
set_directive_pipeline tpu_layer_3/VITIS_LOOP_283_2
set_directive_pipeline tpu_layer_3/VITIS_LOOP_287_6
set_directive_pipeline tpu_layer_3/anonymous
set_directive_pipeline tpu_layer_3/anonymous
set_directive_pipeline tpu_layer_2/VITIS_LOOP_180_2
set_directive_pipeline tpu_layer_2/VITIS_LOOP_184_6
set_directive_pipeline tpu_layer_2/anonymous
set_directive_pipeline tpu_layer_2/anonymous
set_directive_pipeline tpu_layer_1/VITIS_LOOP_75_3
set_directive_pipeline tpu_layer_1/VITIS_LOOP_79_7
set_directive_pipeline tpu_layer_1/anonymous
set_directive_pipeline tpu_layer_1/anonymous
# Inferred from Performance Budgeter performance directives
set_directive_loop_flatten tpu_layer_1/VITIS_LOOP_78_6
set_directive_loop_flatten tpu_layer_1/VITIS_LOOP_77_5
set_directive_loop_flatten tpu_layer_1/VITIS_LOOP_76_4
set_directive_loop_flatten tpu_layer_2/VITIS_LOOP_183_5
set_directive_loop_flatten tpu_layer_2/VITIS_LOOP_182_4
set_directive_loop_flatten tpu_layer_2/VITIS_LOOP_181_3
set_directive_loop_flatten tpu_layer_3/VITIS_LOOP_286_5
set_directive_loop_flatten tpu_layer_3/VITIS_LOOP_285_4
set_directive_loop_flatten tpu_layer_3/VITIS_LOOP_284_3
# Inferred from performance & pipeline pragmas/directives
set_directive_inline systolic_8x8<0>
