[hls]
relative_roots=/home/dlohchab/projects/Verilog/DVCON/task_detection_tpu/tpu_integrated_accel
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=scalar_layer_4/VITIS_LOOP_372_1 
syn.directive.pipeline=tpu_layer_3/VITIS_LOOP_283_2 
syn.directive.pipeline=tpu_layer_3/VITIS_LOOP_287_6 
syn.directive.pipeline=tpu_layer_3/anonymous 
syn.directive.pipeline=tpu_layer_3/anonymous 
syn.directive.pipeline=tpu_layer_2/VITIS_LOOP_180_2 
syn.directive.pipeline=tpu_layer_2/VITIS_LOOP_184_6 
syn.directive.pipeline=tpu_layer_2/anonymous 
syn.directive.pipeline=tpu_layer_2/anonymous 
syn.directive.pipeline=tpu_layer_1/VITIS_LOOP_75_3 
syn.directive.pipeline=tpu_layer_1/VITIS_LOOP_79_7 
syn.directive.pipeline=tpu_layer_1/anonymous 
syn.directive.pipeline=tpu_layer_1/anonymous 
# Inferred from Performance Budgeter performance directives
syn.directive.loop_flatten=tpu_layer_1/VITIS_LOOP_78_6  
syn.directive.loop_flatten=tpu_layer_1/VITIS_LOOP_77_5  
syn.directive.loop_flatten=tpu_layer_1/VITIS_LOOP_76_4  
syn.directive.loop_flatten=tpu_layer_2/VITIS_LOOP_183_5  
syn.directive.loop_flatten=tpu_layer_2/VITIS_LOOP_182_4  
syn.directive.loop_flatten=tpu_layer_2/VITIS_LOOP_181_3  
syn.directive.loop_flatten=tpu_layer_3/VITIS_LOOP_286_5  
syn.directive.loop_flatten=tpu_layer_3/VITIS_LOOP_285_4  
syn.directive.loop_flatten=tpu_layer_3/VITIS_LOOP_284_3  
# Inferred from performance & pipeline pragmas/directives
syn.directive.inline=systolic_8x8<0> 


