[hls]
relative_roots=/home/dlohchab/projects/Verilog/DVCON/task_detection_tpu/tpu_integrated_accel
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=tpu_layer_1/VITIS_LOOP_46_1 
syn.directive.pipeline=tpu_layer_1/VITIS_LOOP_47_2 
syn.directive.pipeline=tpu_layer_1/VITIS_LOOP_53_3 
syn.directive.pipeline=tpu_layer_1/VITIS_LOOP_57_7 
syn.directive.pipeline=tpu_layer_1/VITIS_LOOP_72_12 
syn.directive.pipeline=tpu_layer_1/VITIS_LOOP_66_10 
syn.directive.pipeline=tpu_layer_1/anonymous 
syn.directive.pipeline=task_detection_accel/VITIS_LOOP_170_1 
syn.directive.pipeline=task_detection_accel/VITIS_LOOP_84_1 
syn.directive.pipeline=task_detection_accel/VITIS_LOOP_88_5 
syn.directive.pipeline=task_detection_accel/VITIS_LOOP_103_10 
syn.directive.pipeline=task_detection_accel/VITIS_LOOP_97_8 
syn.directive.pipeline=task_detection_accel/anonymous 
syn.directive.pipeline=task_detection_accel/VITIS_LOOP_115_1 
syn.directive.pipeline=task_detection_accel/VITIS_LOOP_119_5 
syn.directive.pipeline=task_detection_accel/VITIS_LOOP_134_10 
syn.directive.pipeline=task_detection_accel/VITIS_LOOP_128_8 
syn.directive.pipeline=task_detection_accel/anonymous 
syn.directive.pipeline=task_detection_accel/VITIS_LOOP_146_1 
# Inferred from Performance Budgeter performance directives
syn.directive.loop_flatten=tpu_layer_1/VITIS_LOOP_56_6  
syn.directive.loop_flatten=tpu_layer_1/VITIS_LOOP_55_5  
syn.directive.loop_flatten=tpu_layer_1/VITIS_LOOP_54_4  
syn.directive.loop_flatten=task_detection_accel/VITIS_LOOP_87_4  
syn.directive.loop_flatten=task_detection_accel/VITIS_LOOP_86_3  
syn.directive.loop_flatten=task_detection_accel/VITIS_LOOP_85_2  
syn.directive.loop_flatten=task_detection_accel/VITIS_LOOP_118_4  
syn.directive.loop_flatten=task_detection_accel/VITIS_LOOP_117_3  
syn.directive.loop_flatten=task_detection_accel/VITIS_LOOP_116_2  
# Inferred from performance & pipeline pragmas/directives
syn.directive.inline=systolic_8x8 
syn.directive.array_partition=tpu_layer_1/w_tile dim=1 type=complete variable=w_tile
syn.directive.array_partition=task_detection_accel/w_tile.i dim=1 type=complete variable=w_tile.i
syn.directive.array_partition=task_detection_accel/w_tile.i33 dim=1 type=complete variable=w_tile.i33


