[hls]
relative_roots=/home/dlohchab/projects/Verilog/DVCON/task_detection_tpu/task_detection_tpu
# Inferred from syn.array_partition.complete_threshold=4
syn.directive.array_partition=task_detection_accel/linear_64_1(float*, float*)::bias dim=1 type=complete variable=linear_64_1(float*, float*)::bias
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=task_detection_accel/VITIS_LOOP_23_2 
syn.directive.pipeline=task_detection_accel/VITIS_LOOP_68_2 
syn.directive.pipeline=task_detection_accel/VITIS_LOOP_113_2 
syn.directive.pipeline=task_detection_accel/VITIS_LOOP_156_1 
# Inferred from Performance Budgeter performance directives
syn.directive.loop_flatten=task_detection_accel/VITIS_LOOP_19_1  
syn.directive.loop_flatten=task_detection_accel/VITIS_LOOP_64_1  
syn.directive.loop_flatten=task_detection_accel/VITIS_LOOP_109_1  
# Inferred from performance & pipeline pragmas/directives
syn.directive.loop_flatten=task_detection_accel/VITIS_LOOP_32_3  
syn.directive.loop_flatten=task_detection_accel/VITIS_LOOP_77_3  
syn.directive.loop_flatten=task_detection_accel/VITIS_LOOP_122_3  


